// Code generated by go-swagger; DO NOT EDIT.

package tapi_virtual_network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsCreateVirtualNetworkServiceOKCode is the HTTP code returned for type PostOperationsCreateVirtualNetworkServiceOK
const PostOperationsCreateVirtualNetworkServiceOKCode int = 200

/*PostOperationsCreateVirtualNetworkServiceOK Correct response

swagger:response postOperationsCreateVirtualNetworkServiceOK
*/
type PostOperationsCreateVirtualNetworkServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiVirtualNetworkCreateVirtualNetworkServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsCreateVirtualNetworkServiceOK creates PostOperationsCreateVirtualNetworkServiceOK with default headers values
func NewPostOperationsCreateVirtualNetworkServiceOK() *PostOperationsCreateVirtualNetworkServiceOK {

	return &PostOperationsCreateVirtualNetworkServiceOK{}
}

// WithPayload adds the payload to the post operations create virtual network service o k response
func (o *PostOperationsCreateVirtualNetworkServiceOK) WithPayload(payload *models.TapiVirtualNetworkCreateVirtualNetworkServiceOutput) *PostOperationsCreateVirtualNetworkServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations create virtual network service o k response
func (o *PostOperationsCreateVirtualNetworkServiceOK) SetPayload(payload *models.TapiVirtualNetworkCreateVirtualNetworkServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsCreateVirtualNetworkServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsCreateVirtualNetworkServiceCreatedCode is the HTTP code returned for type PostOperationsCreateVirtualNetworkServiceCreated
const PostOperationsCreateVirtualNetworkServiceCreatedCode int = 201

/*PostOperationsCreateVirtualNetworkServiceCreated No response

swagger:response postOperationsCreateVirtualNetworkServiceCreated
*/
type PostOperationsCreateVirtualNetworkServiceCreated struct {
}

// NewPostOperationsCreateVirtualNetworkServiceCreated creates PostOperationsCreateVirtualNetworkServiceCreated with default headers values
func NewPostOperationsCreateVirtualNetworkServiceCreated() *PostOperationsCreateVirtualNetworkServiceCreated {

	return &PostOperationsCreateVirtualNetworkServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsCreateVirtualNetworkServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsCreateVirtualNetworkServiceBadRequestCode is the HTTP code returned for type PostOperationsCreateVirtualNetworkServiceBadRequest
const PostOperationsCreateVirtualNetworkServiceBadRequestCode int = 400

/*PostOperationsCreateVirtualNetworkServiceBadRequest Internal error

swagger:response postOperationsCreateVirtualNetworkServiceBadRequest
*/
type PostOperationsCreateVirtualNetworkServiceBadRequest struct {
}

// NewPostOperationsCreateVirtualNetworkServiceBadRequest creates PostOperationsCreateVirtualNetworkServiceBadRequest with default headers values
func NewPostOperationsCreateVirtualNetworkServiceBadRequest() *PostOperationsCreateVirtualNetworkServiceBadRequest {

	return &PostOperationsCreateVirtualNetworkServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsCreateVirtualNetworkServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
