// Code generated by go-swagger; DO NOT EDIT.

package tapi_virtual_network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsGetVirtualNetworkServiceListOKCode is the HTTP code returned for type PostOperationsGetVirtualNetworkServiceListOK
const PostOperationsGetVirtualNetworkServiceListOKCode int = 200

/*PostOperationsGetVirtualNetworkServiceListOK Correct response

swagger:response postOperationsGetVirtualNetworkServiceListOK
*/
type PostOperationsGetVirtualNetworkServiceListOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiVirtualNetworkGetVirtualNetworkServiceListOutput `json:"body,omitempty"`
}

// NewPostOperationsGetVirtualNetworkServiceListOK creates PostOperationsGetVirtualNetworkServiceListOK with default headers values
func NewPostOperationsGetVirtualNetworkServiceListOK() *PostOperationsGetVirtualNetworkServiceListOK {

	return &PostOperationsGetVirtualNetworkServiceListOK{}
}

// WithPayload adds the payload to the post operations get virtual network service list o k response
func (o *PostOperationsGetVirtualNetworkServiceListOK) WithPayload(payload *models.TapiVirtualNetworkGetVirtualNetworkServiceListOutput) *PostOperationsGetVirtualNetworkServiceListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get virtual network service list o k response
func (o *PostOperationsGetVirtualNetworkServiceListOK) SetPayload(payload *models.TapiVirtualNetworkGetVirtualNetworkServiceListOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetVirtualNetworkServiceListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetVirtualNetworkServiceListCreatedCode is the HTTP code returned for type PostOperationsGetVirtualNetworkServiceListCreated
const PostOperationsGetVirtualNetworkServiceListCreatedCode int = 201

/*PostOperationsGetVirtualNetworkServiceListCreated No response

swagger:response postOperationsGetVirtualNetworkServiceListCreated
*/
type PostOperationsGetVirtualNetworkServiceListCreated struct {
}

// NewPostOperationsGetVirtualNetworkServiceListCreated creates PostOperationsGetVirtualNetworkServiceListCreated with default headers values
func NewPostOperationsGetVirtualNetworkServiceListCreated() *PostOperationsGetVirtualNetworkServiceListCreated {

	return &PostOperationsGetVirtualNetworkServiceListCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetVirtualNetworkServiceListCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetVirtualNetworkServiceListBadRequestCode is the HTTP code returned for type PostOperationsGetVirtualNetworkServiceListBadRequest
const PostOperationsGetVirtualNetworkServiceListBadRequestCode int = 400

/*PostOperationsGetVirtualNetworkServiceListBadRequest Internal error

swagger:response postOperationsGetVirtualNetworkServiceListBadRequest
*/
type PostOperationsGetVirtualNetworkServiceListBadRequest struct {
}

// NewPostOperationsGetVirtualNetworkServiceListBadRequest creates PostOperationsGetVirtualNetworkServiceListBadRequest with default headers values
func NewPostOperationsGetVirtualNetworkServiceListBadRequest() *PostOperationsGetVirtualNetworkServiceListBadRequest {

	return &PostOperationsGetVirtualNetworkServiceListBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetVirtualNetworkServiceListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
