// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsCreateOamServiceEndPointOKCode is the HTTP code returned for type PostOperationsCreateOamServiceEndPointOK
const PostOperationsCreateOamServiceEndPointOKCode int = 200

/*PostOperationsCreateOamServiceEndPointOK Correct response

swagger:response postOperationsCreateOamServiceEndPointOK
*/
type PostOperationsCreateOamServiceEndPointOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiOamCreateOamServiceEndPointOutput `json:"body,omitempty"`
}

// NewPostOperationsCreateOamServiceEndPointOK creates PostOperationsCreateOamServiceEndPointOK with default headers values
func NewPostOperationsCreateOamServiceEndPointOK() *PostOperationsCreateOamServiceEndPointOK {

	return &PostOperationsCreateOamServiceEndPointOK{}
}

// WithPayload adds the payload to the post operations create oam service end point o k response
func (o *PostOperationsCreateOamServiceEndPointOK) WithPayload(payload *models.TapiOamCreateOamServiceEndPointOutput) *PostOperationsCreateOamServiceEndPointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations create oam service end point o k response
func (o *PostOperationsCreateOamServiceEndPointOK) SetPayload(payload *models.TapiOamCreateOamServiceEndPointOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsCreateOamServiceEndPointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsCreateOamServiceEndPointCreatedCode is the HTTP code returned for type PostOperationsCreateOamServiceEndPointCreated
const PostOperationsCreateOamServiceEndPointCreatedCode int = 201

/*PostOperationsCreateOamServiceEndPointCreated No response

swagger:response postOperationsCreateOamServiceEndPointCreated
*/
type PostOperationsCreateOamServiceEndPointCreated struct {
}

// NewPostOperationsCreateOamServiceEndPointCreated creates PostOperationsCreateOamServiceEndPointCreated with default headers values
func NewPostOperationsCreateOamServiceEndPointCreated() *PostOperationsCreateOamServiceEndPointCreated {

	return &PostOperationsCreateOamServiceEndPointCreated{}
}

// WriteResponse to the client
func (o *PostOperationsCreateOamServiceEndPointCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsCreateOamServiceEndPointBadRequestCode is the HTTP code returned for type PostOperationsCreateOamServiceEndPointBadRequest
const PostOperationsCreateOamServiceEndPointBadRequestCode int = 400

/*PostOperationsCreateOamServiceEndPointBadRequest Internal error

swagger:response postOperationsCreateOamServiceEndPointBadRequest
*/
type PostOperationsCreateOamServiceEndPointBadRequest struct {
}

// NewPostOperationsCreateOamServiceEndPointBadRequest creates PostOperationsCreateOamServiceEndPointBadRequest with default headers values
func NewPostOperationsCreateOamServiceEndPointBadRequest() *PostOperationsCreateOamServiceEndPointBadRequest {

	return &PostOperationsCreateOamServiceEndPointBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsCreateOamServiceEndPointBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
