// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/damianoneill/tapi/models"
)

// NewPostOperationsGetOamServiceEndPointParams creates a new PostOperationsGetOamServiceEndPointParams object
// no default values defined in spec.
func NewPostOperationsGetOamServiceEndPointParams() PostOperationsGetOamServiceEndPointParams {

	return PostOperationsGetOamServiceEndPointParams{}
}

// PostOperationsGetOamServiceEndPointParams contains all the bound params for the post operations get oam service end point operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostOperationsGetOamServiceEndPoint
type PostOperationsGetOamServiceEndPointParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	BodyParam *models.TapiOamGetOamServiceEndPointInput
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostOperationsGetOamServiceEndPointParams() beforehand.
func (o *PostOperationsGetOamServiceEndPointParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TapiOamGetOamServiceEndPointInput
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("bodyParam", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BodyParam = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
