// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsGetOamServiceListOKCode is the HTTP code returned for type PostOperationsGetOamServiceListOK
const PostOperationsGetOamServiceListOKCode int = 200

/*PostOperationsGetOamServiceListOK Correct response

swagger:response postOperationsGetOamServiceListOK
*/
type PostOperationsGetOamServiceListOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiOamGetOamServiceListOutput `json:"body,omitempty"`
}

// NewPostOperationsGetOamServiceListOK creates PostOperationsGetOamServiceListOK with default headers values
func NewPostOperationsGetOamServiceListOK() *PostOperationsGetOamServiceListOK {

	return &PostOperationsGetOamServiceListOK{}
}

// WithPayload adds the payload to the post operations get oam service list o k response
func (o *PostOperationsGetOamServiceListOK) WithPayload(payload *models.TapiOamGetOamServiceListOutput) *PostOperationsGetOamServiceListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get oam service list o k response
func (o *PostOperationsGetOamServiceListOK) SetPayload(payload *models.TapiOamGetOamServiceListOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetOamServiceListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetOamServiceListCreatedCode is the HTTP code returned for type PostOperationsGetOamServiceListCreated
const PostOperationsGetOamServiceListCreatedCode int = 201

/*PostOperationsGetOamServiceListCreated No response

swagger:response postOperationsGetOamServiceListCreated
*/
type PostOperationsGetOamServiceListCreated struct {
}

// NewPostOperationsGetOamServiceListCreated creates PostOperationsGetOamServiceListCreated with default headers values
func NewPostOperationsGetOamServiceListCreated() *PostOperationsGetOamServiceListCreated {

	return &PostOperationsGetOamServiceListCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetOamServiceListCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetOamServiceListBadRequestCode is the HTTP code returned for type PostOperationsGetOamServiceListBadRequest
const PostOperationsGetOamServiceListBadRequestCode int = 400

/*PostOperationsGetOamServiceListBadRequest Internal error

swagger:response postOperationsGetOamServiceListBadRequest
*/
type PostOperationsGetOamServiceListBadRequest struct {
}

// NewPostOperationsGetOamServiceListBadRequest creates PostOperationsGetOamServiceListBadRequest with default headers values
func NewPostOperationsGetOamServiceListBadRequest() *PostOperationsGetOamServiceListBadRequest {

	return &PostOperationsGetOamServiceListBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetOamServiceListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
