// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsGetOamJobHandlerFunc turns a function with the right signature into a post operations get oam job handler
type PostOperationsGetOamJobHandlerFunc func(PostOperationsGetOamJobParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsGetOamJobHandlerFunc) Handle(params PostOperationsGetOamJobParams) middleware.Responder {
	return fn(params)
}

// PostOperationsGetOamJobHandler interface for that can handle valid post operations get oam job params
type PostOperationsGetOamJobHandler interface {
	Handle(PostOperationsGetOamJobParams) middleware.Responder
}

// NewPostOperationsGetOamJob creates a new http.Handler for the post operations get oam job operation
func NewPostOperationsGetOamJob(ctx *middleware.Context, handler PostOperationsGetOamJobHandler) *PostOperationsGetOamJob {
	return &PostOperationsGetOamJob{Context: ctx, Handler: handler}
}

/*PostOperationsGetOamJob swagger:route POST /operations/get-oam-job/ tapi-oam postOperationsGetOamJob

PostOperationsGetOamJob post operations get oam job API

*/
type PostOperationsGetOamJob struct {
	Context *middleware.Context
	Handler PostOperationsGetOamJobHandler
}

func (o *PostOperationsGetOamJob) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsGetOamJobParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
