// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsUpdateOamServiceOKCode is the HTTP code returned for type PostOperationsUpdateOamServiceOK
const PostOperationsUpdateOamServiceOKCode int = 200

/*PostOperationsUpdateOamServiceOK Correct response

swagger:response postOperationsUpdateOamServiceOK
*/
type PostOperationsUpdateOamServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiOamUpdateOamServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsUpdateOamServiceOK creates PostOperationsUpdateOamServiceOK with default headers values
func NewPostOperationsUpdateOamServiceOK() *PostOperationsUpdateOamServiceOK {

	return &PostOperationsUpdateOamServiceOK{}
}

// WithPayload adds the payload to the post operations update oam service o k response
func (o *PostOperationsUpdateOamServiceOK) WithPayload(payload *models.TapiOamUpdateOamServiceOutput) *PostOperationsUpdateOamServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations update oam service o k response
func (o *PostOperationsUpdateOamServiceOK) SetPayload(payload *models.TapiOamUpdateOamServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsUpdateOamServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsUpdateOamServiceCreatedCode is the HTTP code returned for type PostOperationsUpdateOamServiceCreated
const PostOperationsUpdateOamServiceCreatedCode int = 201

/*PostOperationsUpdateOamServiceCreated No response

swagger:response postOperationsUpdateOamServiceCreated
*/
type PostOperationsUpdateOamServiceCreated struct {
}

// NewPostOperationsUpdateOamServiceCreated creates PostOperationsUpdateOamServiceCreated with default headers values
func NewPostOperationsUpdateOamServiceCreated() *PostOperationsUpdateOamServiceCreated {

	return &PostOperationsUpdateOamServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateOamServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsUpdateOamServiceBadRequestCode is the HTTP code returned for type PostOperationsUpdateOamServiceBadRequest
const PostOperationsUpdateOamServiceBadRequestCode int = 400

/*PostOperationsUpdateOamServiceBadRequest Internal error

swagger:response postOperationsUpdateOamServiceBadRequest
*/
type PostOperationsUpdateOamServiceBadRequest struct {
}

// NewPostOperationsUpdateOamServiceBadRequest creates PostOperationsUpdateOamServiceBadRequest with default headers values
func NewPostOperationsUpdateOamServiceBadRequest() *PostOperationsUpdateOamServiceBadRequest {

	return &PostOperationsUpdateOamServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateOamServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
