// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsGetMegHandlerFunc turns a function with the right signature into a post operations get meg handler
type PostOperationsGetMegHandlerFunc func(PostOperationsGetMegParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsGetMegHandlerFunc) Handle(params PostOperationsGetMegParams) middleware.Responder {
	return fn(params)
}

// PostOperationsGetMegHandler interface for that can handle valid post operations get meg params
type PostOperationsGetMegHandler interface {
	Handle(PostOperationsGetMegParams) middleware.Responder
}

// NewPostOperationsGetMeg creates a new http.Handler for the post operations get meg operation
func NewPostOperationsGetMeg(ctx *middleware.Context, handler PostOperationsGetMegHandler) *PostOperationsGetMeg {
	return &PostOperationsGetMeg{Context: ctx, Handler: handler}
}

/*PostOperationsGetMeg swagger:route POST /operations/get-meg/ tapi-oam postOperationsGetMeg

PostOperationsGetMeg post operations get meg API

*/
type PostOperationsGetMeg struct {
	Context *middleware.Context
	Handler PostOperationsGetMegHandler
}

func (o *PostOperationsGetMeg) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsGetMegParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
