// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsDeleteOamServiceEndPointHandlerFunc turns a function with the right signature into a post operations delete oam service end point handler
type PostOperationsDeleteOamServiceEndPointHandlerFunc func(PostOperationsDeleteOamServiceEndPointParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsDeleteOamServiceEndPointHandlerFunc) Handle(params PostOperationsDeleteOamServiceEndPointParams) middleware.Responder {
	return fn(params)
}

// PostOperationsDeleteOamServiceEndPointHandler interface for that can handle valid post operations delete oam service end point params
type PostOperationsDeleteOamServiceEndPointHandler interface {
	Handle(PostOperationsDeleteOamServiceEndPointParams) middleware.Responder
}

// NewPostOperationsDeleteOamServiceEndPoint creates a new http.Handler for the post operations delete oam service end point operation
func NewPostOperationsDeleteOamServiceEndPoint(ctx *middleware.Context, handler PostOperationsDeleteOamServiceEndPointHandler) *PostOperationsDeleteOamServiceEndPoint {
	return &PostOperationsDeleteOamServiceEndPoint{Context: ctx, Handler: handler}
}

/*PostOperationsDeleteOamServiceEndPoint swagger:route POST /operations/delete-oam-service-end-point/ tapi-oam postOperationsDeleteOamServiceEndPoint

PostOperationsDeleteOamServiceEndPoint post operations delete oam service end point API

*/
type PostOperationsDeleteOamServiceEndPoint struct {
	Context *middleware.Context
	Handler PostOperationsDeleteOamServiceEndPointHandler
}

func (o *PostOperationsDeleteOamServiceEndPoint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsDeleteOamServiceEndPointParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
