// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOperationsDeleteOamServiceEndPointCreatedCode is the HTTP code returned for type PostOperationsDeleteOamServiceEndPointCreated
const PostOperationsDeleteOamServiceEndPointCreatedCode int = 201

/*PostOperationsDeleteOamServiceEndPointCreated No response

swagger:response postOperationsDeleteOamServiceEndPointCreated
*/
type PostOperationsDeleteOamServiceEndPointCreated struct {
}

// NewPostOperationsDeleteOamServiceEndPointCreated creates PostOperationsDeleteOamServiceEndPointCreated with default headers values
func NewPostOperationsDeleteOamServiceEndPointCreated() *PostOperationsDeleteOamServiceEndPointCreated {

	return &PostOperationsDeleteOamServiceEndPointCreated{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteOamServiceEndPointCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsDeleteOamServiceEndPointBadRequestCode is the HTTP code returned for type PostOperationsDeleteOamServiceEndPointBadRequest
const PostOperationsDeleteOamServiceEndPointBadRequestCode int = 400

/*PostOperationsDeleteOamServiceEndPointBadRequest Internal error

swagger:response postOperationsDeleteOamServiceEndPointBadRequest
*/
type PostOperationsDeleteOamServiceEndPointBadRequest struct {
}

// NewPostOperationsDeleteOamServiceEndPointBadRequest creates PostOperationsDeleteOamServiceEndPointBadRequest with default headers values
func NewPostOperationsDeleteOamServiceEndPointBadRequest() *PostOperationsDeleteOamServiceEndPointBadRequest {

	return &PostOperationsDeleteOamServiceEndPointBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteOamServiceEndPointBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
