// Code generated by go-swagger; DO NOT EDIT.

package tapi_oam

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOperationsDeleteOamJobCreatedCode is the HTTP code returned for type PostOperationsDeleteOamJobCreated
const PostOperationsDeleteOamJobCreatedCode int = 201

/*PostOperationsDeleteOamJobCreated No response

swagger:response postOperationsDeleteOamJobCreated
*/
type PostOperationsDeleteOamJobCreated struct {
}

// NewPostOperationsDeleteOamJobCreated creates PostOperationsDeleteOamJobCreated with default headers values
func NewPostOperationsDeleteOamJobCreated() *PostOperationsDeleteOamJobCreated {

	return &PostOperationsDeleteOamJobCreated{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteOamJobCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsDeleteOamJobBadRequestCode is the HTTP code returned for type PostOperationsDeleteOamJobBadRequest
const PostOperationsDeleteOamJobBadRequestCode int = 400

/*PostOperationsDeleteOamJobBadRequest Internal error

swagger:response postOperationsDeleteOamJobBadRequest
*/
type PostOperationsDeleteOamJobBadRequest struct {
}

// NewPostOperationsDeleteOamJobBadRequest creates PostOperationsDeleteOamJobBadRequest with default headers values
func NewPostOperationsDeleteOamJobBadRequest() *PostOperationsDeleteOamJobBadRequest {

	return &PostOperationsDeleteOamJobBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteOamJobBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
