// Code generated by go-swagger; DO NOT EDIT.

package tapi_network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostOperationsDeleteNetworkElementCreatedCode is the HTTP code returned for type PostOperationsDeleteNetworkElementCreated
const PostOperationsDeleteNetworkElementCreatedCode int = 201

/*PostOperationsDeleteNetworkElementCreated No response

swagger:response postOperationsDeleteNetworkElementCreated
*/
type PostOperationsDeleteNetworkElementCreated struct {
}

// NewPostOperationsDeleteNetworkElementCreated creates PostOperationsDeleteNetworkElementCreated with default headers values
func NewPostOperationsDeleteNetworkElementCreated() *PostOperationsDeleteNetworkElementCreated {

	return &PostOperationsDeleteNetworkElementCreated{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteNetworkElementCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsDeleteNetworkElementBadRequestCode is the HTTP code returned for type PostOperationsDeleteNetworkElementBadRequest
const PostOperationsDeleteNetworkElementBadRequestCode int = 400

/*PostOperationsDeleteNetworkElementBadRequest Internal error

swagger:response postOperationsDeleteNetworkElementBadRequest
*/
type PostOperationsDeleteNetworkElementBadRequest struct {
}

// NewPostOperationsDeleteNetworkElementBadRequest creates PostOperationsDeleteNetworkElementBadRequest with default headers values
func NewPostOperationsDeleteNetworkElementBadRequest() *PostOperationsDeleteNetworkElementBadRequest {

	return &PostOperationsDeleteNetworkElementBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsDeleteNetworkElementBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
