// Code generated by go-swagger; DO NOT EDIT.

package tapi_network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsGetNetworkElementDetailsOKCode is the HTTP code returned for type PostOperationsGetNetworkElementDetailsOK
const PostOperationsGetNetworkElementDetailsOKCode int = 200

/*PostOperationsGetNetworkElementDetailsOK Correct response

swagger:response postOperationsGetNetworkElementDetailsOK
*/
type PostOperationsGetNetworkElementDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNetworkElementGetNetworkElementDetailsOutput `json:"body,omitempty"`
}

// NewPostOperationsGetNetworkElementDetailsOK creates PostOperationsGetNetworkElementDetailsOK with default headers values
func NewPostOperationsGetNetworkElementDetailsOK() *PostOperationsGetNetworkElementDetailsOK {

	return &PostOperationsGetNetworkElementDetailsOK{}
}

// WithPayload adds the payload to the post operations get network element details o k response
func (o *PostOperationsGetNetworkElementDetailsOK) WithPayload(payload *models.TapiNetworkElementGetNetworkElementDetailsOutput) *PostOperationsGetNetworkElementDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get network element details o k response
func (o *PostOperationsGetNetworkElementDetailsOK) SetPayload(payload *models.TapiNetworkElementGetNetworkElementDetailsOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetNetworkElementDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetNetworkElementDetailsCreatedCode is the HTTP code returned for type PostOperationsGetNetworkElementDetailsCreated
const PostOperationsGetNetworkElementDetailsCreatedCode int = 201

/*PostOperationsGetNetworkElementDetailsCreated No response

swagger:response postOperationsGetNetworkElementDetailsCreated
*/
type PostOperationsGetNetworkElementDetailsCreated struct {
}

// NewPostOperationsGetNetworkElementDetailsCreated creates PostOperationsGetNetworkElementDetailsCreated with default headers values
func NewPostOperationsGetNetworkElementDetailsCreated() *PostOperationsGetNetworkElementDetailsCreated {

	return &PostOperationsGetNetworkElementDetailsCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetNetworkElementDetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetNetworkElementDetailsBadRequestCode is the HTTP code returned for type PostOperationsGetNetworkElementDetailsBadRequest
const PostOperationsGetNetworkElementDetailsBadRequestCode int = 400

/*PostOperationsGetNetworkElementDetailsBadRequest Internal error

swagger:response postOperationsGetNetworkElementDetailsBadRequest
*/
type PostOperationsGetNetworkElementDetailsBadRequest struct {
}

// NewPostOperationsGetNetworkElementDetailsBadRequest creates PostOperationsGetNetworkElementDetailsBadRequest with default headers values
func NewPostOperationsGetNetworkElementDetailsBadRequest() *PostOperationsGetNetworkElementDetailsBadRequest {

	return &PostOperationsGetNetworkElementDetailsBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetNetworkElementDetailsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
