// Code generated by go-swagger; DO NOT EDIT.

package tapi_network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsCreateNetworkElementOKCode is the HTTP code returned for type PostOperationsCreateNetworkElementOK
const PostOperationsCreateNetworkElementOKCode int = 200

/*PostOperationsCreateNetworkElementOK Correct response

swagger:response postOperationsCreateNetworkElementOK
*/
type PostOperationsCreateNetworkElementOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNetworkElementCreateNetworkElementOutput `json:"body,omitempty"`
}

// NewPostOperationsCreateNetworkElementOK creates PostOperationsCreateNetworkElementOK with default headers values
func NewPostOperationsCreateNetworkElementOK() *PostOperationsCreateNetworkElementOK {

	return &PostOperationsCreateNetworkElementOK{}
}

// WithPayload adds the payload to the post operations create network element o k response
func (o *PostOperationsCreateNetworkElementOK) WithPayload(payload *models.TapiNetworkElementCreateNetworkElementOutput) *PostOperationsCreateNetworkElementOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations create network element o k response
func (o *PostOperationsCreateNetworkElementOK) SetPayload(payload *models.TapiNetworkElementCreateNetworkElementOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsCreateNetworkElementOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsCreateNetworkElementCreatedCode is the HTTP code returned for type PostOperationsCreateNetworkElementCreated
const PostOperationsCreateNetworkElementCreatedCode int = 201

/*PostOperationsCreateNetworkElementCreated No response

swagger:response postOperationsCreateNetworkElementCreated
*/
type PostOperationsCreateNetworkElementCreated struct {
}

// NewPostOperationsCreateNetworkElementCreated creates PostOperationsCreateNetworkElementCreated with default headers values
func NewPostOperationsCreateNetworkElementCreated() *PostOperationsCreateNetworkElementCreated {

	return &PostOperationsCreateNetworkElementCreated{}
}

// WriteResponse to the client
func (o *PostOperationsCreateNetworkElementCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsCreateNetworkElementBadRequestCode is the HTTP code returned for type PostOperationsCreateNetworkElementBadRequest
const PostOperationsCreateNetworkElementBadRequestCode int = 400

/*PostOperationsCreateNetworkElementBadRequest Internal error

swagger:response postOperationsCreateNetworkElementBadRequest
*/
type PostOperationsCreateNetworkElementBadRequest struct {
}

// NewPostOperationsCreateNetworkElementBadRequest creates PostOperationsCreateNetworkElementBadRequest with default headers values
func NewPostOperationsCreateNetworkElementBadRequest() *PostOperationsCreateNetworkElementBadRequest {

	return &PostOperationsCreateNetworkElementBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsCreateNetworkElementBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
