// Code generated by go-swagger; DO NOT EDIT.

package tapi_network_element

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsDeleteNetworkElementHandlerFunc turns a function with the right signature into a post operations delete network element handler
type PostOperationsDeleteNetworkElementHandlerFunc func(PostOperationsDeleteNetworkElementParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsDeleteNetworkElementHandlerFunc) Handle(params PostOperationsDeleteNetworkElementParams) middleware.Responder {
	return fn(params)
}

// PostOperationsDeleteNetworkElementHandler interface for that can handle valid post operations delete network element params
type PostOperationsDeleteNetworkElementHandler interface {
	Handle(PostOperationsDeleteNetworkElementParams) middleware.Responder
}

// NewPostOperationsDeleteNetworkElement creates a new http.Handler for the post operations delete network element operation
func NewPostOperationsDeleteNetworkElement(ctx *middleware.Context, handler PostOperationsDeleteNetworkElementHandler) *PostOperationsDeleteNetworkElement {
	return &PostOperationsDeleteNetworkElement{Context: ctx, Handler: handler}
}

/*PostOperationsDeleteNetworkElement swagger:route POST /operations/delete-network-element/ tapi-network-element postOperationsDeleteNetworkElement

PostOperationsDeleteNetworkElement post operations delete network element API

*/
type PostOperationsDeleteNetworkElement struct {
	Context *middleware.Context
	Handler PostOperationsDeleteNetworkElementHandler
}

func (o *PostOperationsDeleteNetworkElement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsDeleteNetworkElementParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
