// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsUpdateNotificationSubscriptionServiceOKCode is the HTTP code returned for type PostOperationsUpdateNotificationSubscriptionServiceOK
const PostOperationsUpdateNotificationSubscriptionServiceOKCode int = 200

/*PostOperationsUpdateNotificationSubscriptionServiceOK Correct response

swagger:response postOperationsUpdateNotificationSubscriptionServiceOK
*/
type PostOperationsUpdateNotificationSubscriptionServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNotificationUpdateNotificationSubscriptionServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsUpdateNotificationSubscriptionServiceOK creates PostOperationsUpdateNotificationSubscriptionServiceOK with default headers values
func NewPostOperationsUpdateNotificationSubscriptionServiceOK() *PostOperationsUpdateNotificationSubscriptionServiceOK {

	return &PostOperationsUpdateNotificationSubscriptionServiceOK{}
}

// WithPayload adds the payload to the post operations update notification subscription service o k response
func (o *PostOperationsUpdateNotificationSubscriptionServiceOK) WithPayload(payload *models.TapiNotificationUpdateNotificationSubscriptionServiceOutput) *PostOperationsUpdateNotificationSubscriptionServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations update notification subscription service o k response
func (o *PostOperationsUpdateNotificationSubscriptionServiceOK) SetPayload(payload *models.TapiNotificationUpdateNotificationSubscriptionServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsUpdateNotificationSubscriptionServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsUpdateNotificationSubscriptionServiceCreatedCode is the HTTP code returned for type PostOperationsUpdateNotificationSubscriptionServiceCreated
const PostOperationsUpdateNotificationSubscriptionServiceCreatedCode int = 201

/*PostOperationsUpdateNotificationSubscriptionServiceCreated No response

swagger:response postOperationsUpdateNotificationSubscriptionServiceCreated
*/
type PostOperationsUpdateNotificationSubscriptionServiceCreated struct {
}

// NewPostOperationsUpdateNotificationSubscriptionServiceCreated creates PostOperationsUpdateNotificationSubscriptionServiceCreated with default headers values
func NewPostOperationsUpdateNotificationSubscriptionServiceCreated() *PostOperationsUpdateNotificationSubscriptionServiceCreated {

	return &PostOperationsUpdateNotificationSubscriptionServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateNotificationSubscriptionServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsUpdateNotificationSubscriptionServiceBadRequestCode is the HTTP code returned for type PostOperationsUpdateNotificationSubscriptionServiceBadRequest
const PostOperationsUpdateNotificationSubscriptionServiceBadRequestCode int = 400

/*PostOperationsUpdateNotificationSubscriptionServiceBadRequest Internal error

swagger:response postOperationsUpdateNotificationSubscriptionServiceBadRequest
*/
type PostOperationsUpdateNotificationSubscriptionServiceBadRequest struct {
}

// NewPostOperationsUpdateNotificationSubscriptionServiceBadRequest creates PostOperationsUpdateNotificationSubscriptionServiceBadRequest with default headers values
func NewPostOperationsUpdateNotificationSubscriptionServiceBadRequest() *PostOperationsUpdateNotificationSubscriptionServiceBadRequest {

	return &PostOperationsUpdateNotificationSubscriptionServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsUpdateNotificationSubscriptionServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
