// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsCreateNotificationSubscriptionServiceHandlerFunc turns a function with the right signature into a post operations create notification subscription service handler
type PostOperationsCreateNotificationSubscriptionServiceHandlerFunc func(PostOperationsCreateNotificationSubscriptionServiceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsCreateNotificationSubscriptionServiceHandlerFunc) Handle(params PostOperationsCreateNotificationSubscriptionServiceParams) middleware.Responder {
	return fn(params)
}

// PostOperationsCreateNotificationSubscriptionServiceHandler interface for that can handle valid post operations create notification subscription service params
type PostOperationsCreateNotificationSubscriptionServiceHandler interface {
	Handle(PostOperationsCreateNotificationSubscriptionServiceParams) middleware.Responder
}

// NewPostOperationsCreateNotificationSubscriptionService creates a new http.Handler for the post operations create notification subscription service operation
func NewPostOperationsCreateNotificationSubscriptionService(ctx *middleware.Context, handler PostOperationsCreateNotificationSubscriptionServiceHandler) *PostOperationsCreateNotificationSubscriptionService {
	return &PostOperationsCreateNotificationSubscriptionService{Context: ctx, Handler: handler}
}

/*PostOperationsCreateNotificationSubscriptionService swagger:route POST /operations/create-notification-subscription-service/ tapi-notification postOperationsCreateNotificationSubscriptionService

PostOperationsCreateNotificationSubscriptionService post operations create notification subscription service API

*/
type PostOperationsCreateNotificationSubscriptionService struct {
	Context *middleware.Context
	Handler PostOperationsCreateNotificationSubscriptionServiceHandler
}

func (o *PostOperationsCreateNotificationSubscriptionService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsCreateNotificationSubscriptionServiceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
