// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsGetNotificationListOKCode is the HTTP code returned for type PostOperationsGetNotificationListOK
const PostOperationsGetNotificationListOKCode int = 200

/*PostOperationsGetNotificationListOK Correct response

swagger:response postOperationsGetNotificationListOK
*/
type PostOperationsGetNotificationListOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNotificationGetNotificationListOutput `json:"body,omitempty"`
}

// NewPostOperationsGetNotificationListOK creates PostOperationsGetNotificationListOK with default headers values
func NewPostOperationsGetNotificationListOK() *PostOperationsGetNotificationListOK {

	return &PostOperationsGetNotificationListOK{}
}

// WithPayload adds the payload to the post operations get notification list o k response
func (o *PostOperationsGetNotificationListOK) WithPayload(payload *models.TapiNotificationGetNotificationListOutput) *PostOperationsGetNotificationListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get notification list o k response
func (o *PostOperationsGetNotificationListOK) SetPayload(payload *models.TapiNotificationGetNotificationListOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetNotificationListCreatedCode is the HTTP code returned for type PostOperationsGetNotificationListCreated
const PostOperationsGetNotificationListCreatedCode int = 201

/*PostOperationsGetNotificationListCreated No response

swagger:response postOperationsGetNotificationListCreated
*/
type PostOperationsGetNotificationListCreated struct {
}

// NewPostOperationsGetNotificationListCreated creates PostOperationsGetNotificationListCreated with default headers values
func NewPostOperationsGetNotificationListCreated() *PostOperationsGetNotificationListCreated {

	return &PostOperationsGetNotificationListCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationListCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetNotificationListBadRequestCode is the HTTP code returned for type PostOperationsGetNotificationListBadRequest
const PostOperationsGetNotificationListBadRequestCode int = 400

/*PostOperationsGetNotificationListBadRequest Internal error

swagger:response postOperationsGetNotificationListBadRequest
*/
type PostOperationsGetNotificationListBadRequest struct {
}

// NewPostOperationsGetNotificationListBadRequest creates PostOperationsGetNotificationListBadRequest with default headers values
func NewPostOperationsGetNotificationListBadRequest() *PostOperationsGetNotificationListBadRequest {

	return &PostOperationsGetNotificationListBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
