// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostOperationsDeleteNotificationSubscriptionServiceHandlerFunc turns a function with the right signature into a post operations delete notification subscription service handler
type PostOperationsDeleteNotificationSubscriptionServiceHandlerFunc func(PostOperationsDeleteNotificationSubscriptionServiceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostOperationsDeleteNotificationSubscriptionServiceHandlerFunc) Handle(params PostOperationsDeleteNotificationSubscriptionServiceParams) middleware.Responder {
	return fn(params)
}

// PostOperationsDeleteNotificationSubscriptionServiceHandler interface for that can handle valid post operations delete notification subscription service params
type PostOperationsDeleteNotificationSubscriptionServiceHandler interface {
	Handle(PostOperationsDeleteNotificationSubscriptionServiceParams) middleware.Responder
}

// NewPostOperationsDeleteNotificationSubscriptionService creates a new http.Handler for the post operations delete notification subscription service operation
func NewPostOperationsDeleteNotificationSubscriptionService(ctx *middleware.Context, handler PostOperationsDeleteNotificationSubscriptionServiceHandler) *PostOperationsDeleteNotificationSubscriptionService {
	return &PostOperationsDeleteNotificationSubscriptionService{Context: ctx, Handler: handler}
}

/*PostOperationsDeleteNotificationSubscriptionService swagger:route POST /operations/delete-notification-subscription-service/ tapi-notification postOperationsDeleteNotificationSubscriptionService

PostOperationsDeleteNotificationSubscriptionService post operations delete notification subscription service API

*/
type PostOperationsDeleteNotificationSubscriptionService struct {
	Context *middleware.Context
	Handler PostOperationsDeleteNotificationSubscriptionServiceHandler
}

func (o *PostOperationsDeleteNotificationSubscriptionService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostOperationsDeleteNotificationSubscriptionServiceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
