// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsGetNotificationSubscriptionServiceDetailsOKCode is the HTTP code returned for type PostOperationsGetNotificationSubscriptionServiceDetailsOK
const PostOperationsGetNotificationSubscriptionServiceDetailsOKCode int = 200

/*PostOperationsGetNotificationSubscriptionServiceDetailsOK Correct response

swagger:response postOperationsGetNotificationSubscriptionServiceDetailsOK
*/
type PostOperationsGetNotificationSubscriptionServiceDetailsOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNotificationGetNotificationSubscriptionServiceDetailsOutput `json:"body,omitempty"`
}

// NewPostOperationsGetNotificationSubscriptionServiceDetailsOK creates PostOperationsGetNotificationSubscriptionServiceDetailsOK with default headers values
func NewPostOperationsGetNotificationSubscriptionServiceDetailsOK() *PostOperationsGetNotificationSubscriptionServiceDetailsOK {

	return &PostOperationsGetNotificationSubscriptionServiceDetailsOK{}
}

// WithPayload adds the payload to the post operations get notification subscription service details o k response
func (o *PostOperationsGetNotificationSubscriptionServiceDetailsOK) WithPayload(payload *models.TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) *PostOperationsGetNotificationSubscriptionServiceDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations get notification subscription service details o k response
func (o *PostOperationsGetNotificationSubscriptionServiceDetailsOK) SetPayload(payload *models.TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationSubscriptionServiceDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsGetNotificationSubscriptionServiceDetailsCreatedCode is the HTTP code returned for type PostOperationsGetNotificationSubscriptionServiceDetailsCreated
const PostOperationsGetNotificationSubscriptionServiceDetailsCreatedCode int = 201

/*PostOperationsGetNotificationSubscriptionServiceDetailsCreated No response

swagger:response postOperationsGetNotificationSubscriptionServiceDetailsCreated
*/
type PostOperationsGetNotificationSubscriptionServiceDetailsCreated struct {
}

// NewPostOperationsGetNotificationSubscriptionServiceDetailsCreated creates PostOperationsGetNotificationSubscriptionServiceDetailsCreated with default headers values
func NewPostOperationsGetNotificationSubscriptionServiceDetailsCreated() *PostOperationsGetNotificationSubscriptionServiceDetailsCreated {

	return &PostOperationsGetNotificationSubscriptionServiceDetailsCreated{}
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationSubscriptionServiceDetailsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsGetNotificationSubscriptionServiceDetailsBadRequestCode is the HTTP code returned for type PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest
const PostOperationsGetNotificationSubscriptionServiceDetailsBadRequestCode int = 400

/*PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest Internal error

swagger:response postOperationsGetNotificationSubscriptionServiceDetailsBadRequest
*/
type PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest struct {
}

// NewPostOperationsGetNotificationSubscriptionServiceDetailsBadRequest creates PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest with default headers values
func NewPostOperationsGetNotificationSubscriptionServiceDetailsBadRequest() *PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest {

	return &PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsGetNotificationSubscriptionServiceDetailsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
