// Code generated by go-swagger; DO NOT EDIT.

package tapi_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/damianoneill/tapi/models"
)

// PostOperationsCreateNotificationSubscriptionServiceOKCode is the HTTP code returned for type PostOperationsCreateNotificationSubscriptionServiceOK
const PostOperationsCreateNotificationSubscriptionServiceOKCode int = 200

/*PostOperationsCreateNotificationSubscriptionServiceOK Correct response

swagger:response postOperationsCreateNotificationSubscriptionServiceOK
*/
type PostOperationsCreateNotificationSubscriptionServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TapiNotificationCreateNotificationSubscriptionServiceOutput `json:"body,omitempty"`
}

// NewPostOperationsCreateNotificationSubscriptionServiceOK creates PostOperationsCreateNotificationSubscriptionServiceOK with default headers values
func NewPostOperationsCreateNotificationSubscriptionServiceOK() *PostOperationsCreateNotificationSubscriptionServiceOK {

	return &PostOperationsCreateNotificationSubscriptionServiceOK{}
}

// WithPayload adds the payload to the post operations create notification subscription service o k response
func (o *PostOperationsCreateNotificationSubscriptionServiceOK) WithPayload(payload *models.TapiNotificationCreateNotificationSubscriptionServiceOutput) *PostOperationsCreateNotificationSubscriptionServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post operations create notification subscription service o k response
func (o *PostOperationsCreateNotificationSubscriptionServiceOK) SetPayload(payload *models.TapiNotificationCreateNotificationSubscriptionServiceOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOperationsCreateNotificationSubscriptionServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostOperationsCreateNotificationSubscriptionServiceCreatedCode is the HTTP code returned for type PostOperationsCreateNotificationSubscriptionServiceCreated
const PostOperationsCreateNotificationSubscriptionServiceCreatedCode int = 201

/*PostOperationsCreateNotificationSubscriptionServiceCreated No response

swagger:response postOperationsCreateNotificationSubscriptionServiceCreated
*/
type PostOperationsCreateNotificationSubscriptionServiceCreated struct {
}

// NewPostOperationsCreateNotificationSubscriptionServiceCreated creates PostOperationsCreateNotificationSubscriptionServiceCreated with default headers values
func NewPostOperationsCreateNotificationSubscriptionServiceCreated() *PostOperationsCreateNotificationSubscriptionServiceCreated {

	return &PostOperationsCreateNotificationSubscriptionServiceCreated{}
}

// WriteResponse to the client
func (o *PostOperationsCreateNotificationSubscriptionServiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostOperationsCreateNotificationSubscriptionServiceBadRequestCode is the HTTP code returned for type PostOperationsCreateNotificationSubscriptionServiceBadRequest
const PostOperationsCreateNotificationSubscriptionServiceBadRequestCode int = 400

/*PostOperationsCreateNotificationSubscriptionServiceBadRequest Internal error

swagger:response postOperationsCreateNotificationSubscriptionServiceBadRequest
*/
type PostOperationsCreateNotificationSubscriptionServiceBadRequest struct {
}

// NewPostOperationsCreateNotificationSubscriptionServiceBadRequest creates PostOperationsCreateNotificationSubscriptionServiceBadRequest with default headers values
func NewPostOperationsCreateNotificationSubscriptionServiceBadRequest() *PostOperationsCreateNotificationSubscriptionServiceBadRequest {

	return &PostOperationsCreateNotificationSubscriptionServiceBadRequest{}
}

// WriteResponse to the client
func (o *PostOperationsCreateNotificationSubscriptionServiceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
