// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiEthBandwidthReport tapi eth bandwidth report
// swagger:model tapi.eth.BandwidthReport
type TapiEthBandwidthReport struct {

	// This attribute returns the current bandwidth.
	CurrentBandwidth int32 `json:"current-bandwidth,omitempty"`

	// This attribute returns the configured bandwidth
	NominalBandwidth int32 `json:"nominal-bandwidth,omitempty"`

	// This attribute returns the far end port identifier.
	PortID int32 `json:"port-id,omitempty"`

	// The sourceMacAddress is the address from the far end.
	SourceMacAddress string `json:"source-mac-address,omitempty"`
}

// Validate validates this tapi eth bandwidth report
func (m *TapiEthBandwidthReport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthBandwidthReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthBandwidthReport) UnmarshalBinary(b []byte) error {
	var res TapiEthBandwidthReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
