// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthPmCurrentDataAugmentation10 tapi eth pm current data augmentation10
// swagger:model tapi.eth.PmCurrentDataAugmentation10
type TapiEthPmCurrentDataAugmentation10 struct {

	// none
	EthOnDemand1LmPerformanceData *TapiEthEthOnDemand1LmPerformanceData `json:"eth-on-demand-1-lm-performance-data,omitempty"`
}

// Validate validates this tapi eth pm current data augmentation10
func (m *TapiEthPmCurrentDataAugmentation10) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthOnDemand1LmPerformanceData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthPmCurrentDataAugmentation10) validateEthOnDemand1LmPerformanceData(formats strfmt.Registry) error {

	if swag.IsZero(m.EthOnDemand1LmPerformanceData) { // not required
		return nil
	}

	if m.EthOnDemand1LmPerformanceData != nil {
		if err := m.EthOnDemand1LmPerformanceData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-on-demand-1-lm-performance-data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthPmCurrentDataAugmentation10) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthPmCurrentDataAugmentation10) UnmarshalBinary(b []byte) error {
	var res TapiEthPmCurrentDataAugmentation10
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
