// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiNotificationNotificationType tapi notification notification type
// swagger:model tapi.notification.NotificationType
type TapiNotificationNotificationType string

const (

	// TapiNotificationNotificationTypeOBJECTCREATION captures enum value "OBJECT_CREATION"
	TapiNotificationNotificationTypeOBJECTCREATION TapiNotificationNotificationType = "OBJECT_CREATION"

	// TapiNotificationNotificationTypeOBJECTDELETION captures enum value "OBJECT_DELETION"
	TapiNotificationNotificationTypeOBJECTDELETION TapiNotificationNotificationType = "OBJECT_DELETION"

	// TapiNotificationNotificationTypeATTRIBUTEVALUECHANGE captures enum value "ATTRIBUTE_VALUE_CHANGE"
	TapiNotificationNotificationTypeATTRIBUTEVALUECHANGE TapiNotificationNotificationType = "ATTRIBUTE_VALUE_CHANGE"

	// TapiNotificationNotificationTypeALARMEVENT captures enum value "ALARM_EVENT"
	TapiNotificationNotificationTypeALARMEVENT TapiNotificationNotificationType = "ALARM_EVENT"

	// TapiNotificationNotificationTypeTHRESHOLDCROSSINGALERT captures enum value "THRESHOLD_CROSSING_ALERT"
	TapiNotificationNotificationTypeTHRESHOLDCROSSINGALERT TapiNotificationNotificationType = "THRESHOLD_CROSSING_ALERT"
)

// for schema
var tapiNotificationNotificationTypeEnum []interface{}

func init() {
	var res []TapiNotificationNotificationType
	if err := json.Unmarshal([]byte(`["OBJECT_CREATION","OBJECT_DELETION","ATTRIBUTE_VALUE_CHANGE","ALARM_EVENT","THRESHOLD_CROSSING_ALERT"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiNotificationNotificationTypeEnum = append(tapiNotificationNotificationTypeEnum, v)
	}
}

func (m TapiNotificationNotificationType) validateTapiNotificationNotificationTypeEnum(path, location string, value TapiNotificationNotificationType) error {
	if err := validate.Enum(path, location, value, tapiNotificationNotificationTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi notification notification type
func (m TapiNotificationNotificationType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiNotificationNotificationTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
