// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiVirtualNetworkVirtualNwServiceRef tapi virtual network virtual nw service ref
// swagger:model tapi.virtual.network.VirtualNwServiceRef
type TapiVirtualNetworkVirtualNwServiceRef struct {

	// none
	VirtualNwServiceUUID string `json:"virtual-nw-service-uuid,omitempty"`
}

// Validate validates this tapi virtual network virtual nw service ref
func (m *TapiVirtualNetworkVirtualNwServiceRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkVirtualNwServiceRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkVirtualNwServiceRef) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkVirtualNwServiceRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
