// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiPhotonicMediaMediaChannelServiceInterfacePointSpec tapi photonic media media channel service interface point spec
// swagger:model tapi.photonic.media.MediaChannelServiceInterfacePointSpec
type TapiPhotonicMediaMediaChannelServiceInterfacePointSpec struct {

	// none
	McPool *TapiPhotonicMediaMediaChannelPoolCapabilityPac `json:"mc-pool,omitempty"`
}

// Validate validates this tapi photonic media media channel service interface point spec
func (m *TapiPhotonicMediaMediaChannelServiceInterfacePointSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMcPool(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiPhotonicMediaMediaChannelServiceInterfacePointSpec) validateMcPool(formats strfmt.Registry) error {

	if swag.IsZero(m.McPool) { // not required
		return nil
	}

	if m.McPool != nil {
		if err := m.McPool.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mc-pool")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiPhotonicMediaMediaChannelServiceInterfacePointSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiPhotonicMediaMediaChannelServiceInterfacePointSpec) UnmarshalBinary(b []byte) error {
	var res TapiPhotonicMediaMediaChannelServiceInterfacePointSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
