// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiEthOamPduGenerationType tapi eth oam pdu generation type
// swagger:model tapi.eth.OamPduGenerationType
type TapiEthOamPduGenerationType string

const (

	// TapiEthOamPduGenerationTypeSINGLEINSTANCE captures enum value "SINGLE_INSTANCE"
	TapiEthOamPduGenerationTypeSINGLEINSTANCE TapiEthOamPduGenerationType = "SINGLE_INSTANCE"

	// TapiEthOamPduGenerationTypeREPETITIVEINSTANCE captures enum value "REPETITIVE_INSTANCE"
	TapiEthOamPduGenerationTypeREPETITIVEINSTANCE TapiEthOamPduGenerationType = "REPETITIVE_INSTANCE"

	// TapiEthOamPduGenerationTypeSINGLESERIES captures enum value "SINGLE_SERIES"
	TapiEthOamPduGenerationTypeSINGLESERIES TapiEthOamPduGenerationType = "SINGLE_SERIES"

	// TapiEthOamPduGenerationTypeREPETITIVESERIES captures enum value "REPETITIVE_SERIES"
	TapiEthOamPduGenerationTypeREPETITIVESERIES TapiEthOamPduGenerationType = "REPETITIVE_SERIES"
)

// for schema
var tapiEthOamPduGenerationTypeEnum []interface{}

func init() {
	var res []TapiEthOamPduGenerationType
	if err := json.Unmarshal([]byte(`["SINGLE_INSTANCE","REPETITIVE_INSTANCE","SINGLE_SERIES","REPETITIVE_SERIES"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiEthOamPduGenerationTypeEnum = append(tapiEthOamPduGenerationTypeEnum, v)
	}
}

func (m TapiEthOamPduGenerationType) validateTapiEthOamPduGenerationTypeEnum(path, location string, value TapiEthOamPduGenerationType) error {
	if err := validate.Enum(path, location, value, tapiEthOamPduGenerationTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi eth oam pdu generation type
func (m TapiEthOamPduGenerationType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiEthOamPduGenerationTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
