// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduOduConnectionEndPointSpec tapi odu odu connection end point spec
// swagger:model tapi.odu.OduConnectionEndPointSpec
type TapiOduOduConnectionEndPointSpec struct {

	// none
	OduCommon *TapiOduOduCommonPac `json:"odu-common,omitempty"`

	// none
	OduCtp *TapiOduOduCtpPac `json:"odu-ctp,omitempty"`

	// none
	OduProtection *TapiOduOduProtectionPac `json:"odu-protection,omitempty"`

	// none
	OduTermAndAdapter *TapiOduOduTerminationAndClientAdaptationPac `json:"odu-term-and-adapter,omitempty"`
}

// Validate validates this tapi odu odu connection end point spec
func (m *TapiOduOduConnectionEndPointSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOduCommon(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduCtp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduProtection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduTermAndAdapter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduOduConnectionEndPointSpec) validateOduCommon(formats strfmt.Registry) error {

	if swag.IsZero(m.OduCommon) { // not required
		return nil
	}

	if m.OduCommon != nil {
		if err := m.OduCommon.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-common")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduConnectionEndPointSpec) validateOduCtp(formats strfmt.Registry) error {

	if swag.IsZero(m.OduCtp) { // not required
		return nil
	}

	if m.OduCtp != nil {
		if err := m.OduCtp.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-ctp")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduConnectionEndPointSpec) validateOduProtection(formats strfmt.Registry) error {

	if swag.IsZero(m.OduProtection) { // not required
		return nil
	}

	if m.OduProtection != nil {
		if err := m.OduProtection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-protection")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduConnectionEndPointSpec) validateOduTermAndAdapter(formats strfmt.Registry) error {

	if swag.IsZero(m.OduTermAndAdapter) { // not required
		return nil
	}

	if m.OduTermAndAdapter != nil {
		if err := m.OduTermAndAdapter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-term-and-adapter")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduOduConnectionEndPointSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduOduConnectionEndPointSpec) UnmarshalBinary(b []byte) error {
	var res TapiOduOduConnectionEndPointSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
