// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetOamServiceEndPointInput tapi oam get oam service end point input
// swagger:model tapi.oam.GetOamServiceEndPointInput
type TapiOamGetOamServiceEndPointInput struct {

	// input
	Input *TapiOamGetOamServiceEndPointInputInput `json:"input,omitempty"`
}

// Validate validates this tapi oam get oam service end point input
func (m *TapiOamGetOamServiceEndPointInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetOamServiceEndPointInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceEndPointInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceEndPointInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceEndPointInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiOamGetOamServiceEndPointInputInput tapi oam get oam service end point input input
// swagger:model TapiOamGetOamServiceEndPointInputInput
type TapiOamGetOamServiceEndPointInputInput struct {

	// none
	OSepID string `json:"o-sep-id,omitempty"`

	// none
	ServiceID string `json:"service-id,omitempty"`
}

// Validate validates this tapi oam get oam service end point input input
func (m *TapiOamGetOamServiceEndPointInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceEndPointInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceEndPointInputInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceEndPointInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
