// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetOamServiceInput tapi oam get oam service input
// swagger:model tapi.oam.GetOamServiceInput
type TapiOamGetOamServiceInput struct {

	// input
	Input *TapiOamGetOamServiceInputInput `json:"input,omitempty"`
}

// Validate validates this tapi oam get oam service input
func (m *TapiOamGetOamServiceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetOamServiceInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiOamGetOamServiceInputInput tapi oam get oam service input input
// swagger:model TapiOamGetOamServiceInputInput
type TapiOamGetOamServiceInputInput struct {

	// none
	ServiceID string `json:"service-id,omitempty"`
}

// Validate validates this tapi oam get oam service input input
func (m *TapiOamGetOamServiceInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceInputInput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
