// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduOduPayloadType tapi odu odu payload type
// swagger:model tapi.odu.OduPayloadType
type TapiOduOduPayloadType struct {

	// none
	HexPayloadType int32 `json:"hex-payload-type,omitempty"`

	// none
	NamedPayloadType TapiOduOduNamedPayloadType `json:"named-payload-type,omitempty"`
}

// Validate validates this tapi odu odu payload type
func (m *TapiOduOduPayloadType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNamedPayloadType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduOduPayloadType) validateNamedPayloadType(formats strfmt.Registry) error {

	if swag.IsZero(m.NamedPayloadType) { // not required
		return nil
	}

	if err := m.NamedPayloadType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("named-payload-type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduOduPayloadType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduOduPayloadType) UnmarshalBinary(b []byte) error {
	var res TapiOduOduPayloadType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
