// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamMepRef tapi oam mep ref
// swagger:model tapi.oam.MepRef
type TapiOamMepRef struct {
	TapiOamMegRef

	// none
	MepLocalID string `json:"mep-local-id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamMepRef) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiOamMegRef
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiOamMegRef = aO0

	// AO1
	var dataAO1 struct {
		MepLocalID string `json:"mep-local-id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.MepLocalID = dataAO1.MepLocalID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamMepRef) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiOamMegRef)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		MepLocalID string `json:"mep-local-id,omitempty"`
	}

	dataAO1.MepLocalID = m.MepLocalID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam mep ref
func (m *TapiOamMepRef) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiOamMegRef
	if err := m.TapiOamMegRef.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamMepRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamMepRef) UnmarshalBinary(b []byte) error {
	var res TapiOamMepRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
