// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthProActiveLmPerformanceData tapi eth eth pro active lm performance data
// swagger:model tapi.eth.EthProActiveLmPerformanceData
type TapiEthEthProActiveLmPerformanceData struct {

	// This attribute contains the bidirectional UAS (unavailable seconds) detected in the monitoring interval.
	//                     range of type : 0..900 for 15min interval or 0..86400 for 24 hr interval.
	BidirectionalUas int32 `json:"bidirectional-uas,omitempty"`

	// This attribute contains the statistical far end performnace parameters.
	ProActiveFarEndLmParameters *TapiEthStatisticalLmPerformanceParameters `json:"pro-active-far-end-lm-parameters,omitempty"`

	// This attribute contains the statistical near end performnace parameters.
	ProActiveNearEndLmParameters *TapiEthStatisticalLmPerformanceParameters `json:"pro-active-near-end-lm-parameters,omitempty"`
}

// Validate validates this tapi eth eth pro active lm performance data
func (m *TapiEthEthProActiveLmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProActiveFarEndLmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProActiveNearEndLmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthProActiveLmPerformanceData) validateProActiveFarEndLmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveFarEndLmParameters) { // not required
		return nil
	}

	if m.ProActiveFarEndLmParameters != nil {
		if err := m.ProActiveFarEndLmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-far-end-lm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActiveLmPerformanceData) validateProActiveNearEndLmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveNearEndLmParameters) { // not required
		return nil
	}

	if m.ProActiveNearEndLmParameters != nil {
		if err := m.ProActiveNearEndLmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-near-end-lm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthProActiveLmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthProActiveLmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthProActiveLmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
