// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthPmThresholdDataAugmentation3 tapi eth pm threshold data augmentation3
// swagger:model tapi.eth.PmThresholdDataAugmentation3
type TapiEthPmThresholdDataAugmentation3 struct {

	// none
	EthDmThresholdData *TapiEthEthDmThresholdData `json:"eth-dm-threshold-data,omitempty"`
}

// Validate validates this tapi eth pm threshold data augmentation3
func (m *TapiEthPmThresholdDataAugmentation3) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthDmThresholdData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthPmThresholdDataAugmentation3) validateEthDmThresholdData(formats strfmt.Registry) error {

	if swag.IsZero(m.EthDmThresholdData) { // not required
		return nil
	}

	if m.EthDmThresholdData != nil {
		if err := m.EthDmThresholdData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-dm-threshold-data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthPmThresholdDataAugmentation3) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthPmThresholdDataAugmentation3) UnmarshalBinary(b []byte) error {
	var res TapiEthPmThresholdDataAugmentation3
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
