// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduOduMipSpec tapi odu odu mip spec
// swagger:model tapi.odu.OduMipSpec
type TapiOduOduMipSpec struct {

	// none
	OduDefect *TapiOduOduDefectPac `json:"odu-defect,omitempty"`

	// none
	OduMip *TapiOduOduMipPac `json:"odu-mip,omitempty"`

	// none
	OduNcm *TapiOduOduNcmPac `json:"odu-ncm,omitempty"`

	// none
	OduPm *TapiOduOduPmPac `json:"odu-pm,omitempty"`

	// none
	OduTcm *TapiOduOduTcmMipPac `json:"odu-tcm,omitempty"`
}

// Validate validates this tapi odu odu mip spec
func (m *TapiOduOduMipSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOduDefect(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduMip(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduNcm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduPm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOduTcm(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduOduMipSpec) validateOduDefect(formats strfmt.Registry) error {

	if swag.IsZero(m.OduDefect) { // not required
		return nil
	}

	if m.OduDefect != nil {
		if err := m.OduDefect.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-defect")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduMipSpec) validateOduMip(formats strfmt.Registry) error {

	if swag.IsZero(m.OduMip) { // not required
		return nil
	}

	if m.OduMip != nil {
		if err := m.OduMip.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-mip")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduMipSpec) validateOduNcm(formats strfmt.Registry) error {

	if swag.IsZero(m.OduNcm) { // not required
		return nil
	}

	if m.OduNcm != nil {
		if err := m.OduNcm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-ncm")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduMipSpec) validateOduPm(formats strfmt.Registry) error {

	if swag.IsZero(m.OduPm) { // not required
		return nil
	}

	if m.OduPm != nil {
		if err := m.OduPm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-pm")
			}
			return err
		}
	}

	return nil
}

func (m *TapiOduOduMipSpec) validateOduTcm(formats strfmt.Registry) error {

	if swag.IsZero(m.OduTcm) { // not required
		return nil
	}

	if m.OduTcm != nil {
		if err := m.OduTcm.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-tcm")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduOduMipSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduOduMipSpec) UnmarshalBinary(b []byte) error {
	var res TapiOduOduMipSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
