// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthProActive1DmPerformanceData tapi eth eth pro active1 dm performance data
// swagger:model tapi.eth.EthProActive1DmPerformanceData
type TapiEthEthProActive1DmPerformanceData struct {

	// This attribute contains the statistical near end performnace parameters.
	ProActiveNearEnd1DmParameters *TapiEthStatisticalDmPerformanceParameters `json:"pro-active-near-end-1-dm-parameters,omitempty"`
}

// Validate validates this tapi eth eth pro active1 dm performance data
func (m *TapiEthEthProActive1DmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProActiveNearEnd1DmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthProActive1DmPerformanceData) validateProActiveNearEnd1DmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveNearEnd1DmParameters) { // not required
		return nil
	}

	if m.ProActiveNearEnd1DmParameters != nil {
		if err := m.ProActiveNearEnd1DmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-near-end-1-dm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthProActive1DmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthProActive1DmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthProActive1DmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
