// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNetworkElementNetworkElement tapi network element network element
// swagger:model tapi.network.element.NetworkElement
type TapiNetworkElementNetworkElement struct {
	TapiNetworkElementConnection

	TapiNetworkElementSite

	// The Network Element id.
	NetworkElementID string `json:"network-element-id,omitempty"`

	// The last time the Network Element was successfully discovered.
	NetworkElementLastSuccessfulDiscovery string `json:"network-element-lastSuccessfulDiscovery,omitempty"`

	// The Network Element model.
	NetworkElementModel string `json:"network-element-model,omitempty"`

	// The Network Element name.
	NetworkElementName string `json:"network-element-name,omitempty"`

	// The Network Element vendor.
	NetworkElementVendor string `json:"network-element-vendor,omitempty"`

	// The Network Element version.
	NetworkElementVersion string `json:"network-element-version,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiNetworkElementNetworkElement) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiNetworkElementConnection
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiNetworkElementConnection = aO0

	// AO1
	var aO1 TapiNetworkElementSite
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiNetworkElementSite = aO1

	// AO2
	var dataAO2 struct {
		NetworkElementID string `json:"network-element-id,omitempty"`

		NetworkElementLastSuccessfulDiscovery string `json:"network-element-lastSuccessfulDiscovery,omitempty"`

		NetworkElementModel string `json:"network-element-model,omitempty"`

		NetworkElementName string `json:"network-element-name,omitempty"`

		NetworkElementVendor string `json:"network-element-vendor,omitempty"`

		NetworkElementVersion string `json:"network-element-version,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	m.NetworkElementID = dataAO2.NetworkElementID

	m.NetworkElementLastSuccessfulDiscovery = dataAO2.NetworkElementLastSuccessfulDiscovery

	m.NetworkElementModel = dataAO2.NetworkElementModel

	m.NetworkElementName = dataAO2.NetworkElementName

	m.NetworkElementVendor = dataAO2.NetworkElementVendor

	m.NetworkElementVersion = dataAO2.NetworkElementVersion

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiNetworkElementNetworkElement) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.TapiNetworkElementConnection)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiNetworkElementSite)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	var dataAO2 struct {
		NetworkElementID string `json:"network-element-id,omitempty"`

		NetworkElementLastSuccessfulDiscovery string `json:"network-element-lastSuccessfulDiscovery,omitempty"`

		NetworkElementModel string `json:"network-element-model,omitempty"`

		NetworkElementName string `json:"network-element-name,omitempty"`

		NetworkElementVendor string `json:"network-element-vendor,omitempty"`

		NetworkElementVersion string `json:"network-element-version,omitempty"`
	}

	dataAO2.NetworkElementID = m.NetworkElementID

	dataAO2.NetworkElementLastSuccessfulDiscovery = m.NetworkElementLastSuccessfulDiscovery

	dataAO2.NetworkElementModel = m.NetworkElementModel

	dataAO2.NetworkElementName = m.NetworkElementName

	dataAO2.NetworkElementVendor = m.NetworkElementVendor

	dataAO2.NetworkElementVersion = m.NetworkElementVersion

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi network element network element
func (m *TapiNetworkElementNetworkElement) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiNetworkElementConnection
	if err := m.TapiNetworkElementConnection.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiNetworkElementSite
	if err := m.TapiNetworkElementSite.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementNetworkElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementNetworkElement) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementNetworkElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
