// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthPmThresholdDataAugmentation1 tapi eth pm threshold data augmentation1
// swagger:model tapi.eth.PmThresholdDataAugmentation1
type TapiEthPmThresholdDataAugmentation1 struct {

	// none
	EthLmThresholdData *TapiEthEthLmThresholdData `json:"eth-lm-threshold-data,omitempty"`
}

// Validate validates this tapi eth pm threshold data augmentation1
func (m *TapiEthPmThresholdDataAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEthLmThresholdData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthPmThresholdDataAugmentation1) validateEthLmThresholdData(formats strfmt.Registry) error {

	if swag.IsZero(m.EthLmThresholdData) { // not required
		return nil
	}

	if m.EthLmThresholdData != nil {
		if err := m.EthLmThresholdData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eth-lm-threshold-data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthPmThresholdDataAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthPmThresholdDataAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiEthPmThresholdDataAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
