// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOduTimDetMo tapi odu tim det mo
// swagger:model tapi.odu.TimDetMo
type TapiOduTimDetMo string

const (

	// TapiOduTimDetMoDAPI captures enum value "DAPI"
	TapiOduTimDetMoDAPI TapiOduTimDetMo = "DAPI"

	// TapiOduTimDetMoSAPI captures enum value "SAPI"
	TapiOduTimDetMoSAPI TapiOduTimDetMo = "SAPI"

	// TapiOduTimDetMoBOTH captures enum value "BOTH"
	TapiOduTimDetMoBOTH TapiOduTimDetMo = "BOTH"

	// TapiOduTimDetMoOFF captures enum value "OFF"
	TapiOduTimDetMoOFF TapiOduTimDetMo = "OFF"
)

// for schema
var tapiOduTimDetMoEnum []interface{}

func init() {
	var res []TapiOduTimDetMo
	if err := json.Unmarshal([]byte(`["DAPI","SAPI","BOTH","OFF"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOduTimDetMoEnum = append(tapiOduTimDetMoEnum, v)
	}
}

func (m TapiOduTimDetMo) validateTapiOduTimDetMoEnum(path, location string, value TapiOduTimDetMo) error {
	if err := validate.Enum(path, location, value, tapiOduTimDetMoEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi odu tim det mo
func (m TapiOduTimDetMo) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOduTimDetMoEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
