// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiEthMessagePeriod tapi eth message period
// swagger:model tapi.eth.MessagePeriod
type TapiEthMessagePeriod string

const (

	// TapiEthMessagePeriodNr10MS captures enum value "10MS"
	TapiEthMessagePeriodNr10MS TapiEthMessagePeriod = "10MS"

	// TapiEthMessagePeriodNr100MS captures enum value "100MS"
	TapiEthMessagePeriodNr100MS TapiEthMessagePeriod = "100MS"

	// TapiEthMessagePeriodNr1S captures enum value "1S"
	TapiEthMessagePeriodNr1S TapiEthMessagePeriod = "1S"

	// TapiEthMessagePeriodNr10S captures enum value "10S"
	TapiEthMessagePeriodNr10S TapiEthMessagePeriod = "10S"

	// TapiEthMessagePeriodNr0 captures enum value "0"
	TapiEthMessagePeriodNr0 TapiEthMessagePeriod = "0"
)

// for schema
var tapiEthMessagePeriodEnum []interface{}

func init() {
	var res []TapiEthMessagePeriod
	if err := json.Unmarshal([]byte(`["10MS","100MS","1S","10S","0"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiEthMessagePeriodEnum = append(tapiEthMessagePeriodEnum, v)
	}
}

func (m TapiEthMessagePeriod) validateTapiEthMessagePeriodEnum(path, location string, value TapiEthMessagePeriod) error {
	if err := validate.Enum(path, location, value, tapiEthMessagePeriodEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi eth message period
func (m TapiEthMessagePeriod) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiEthMessagePeriodEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
