// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthProActiveDmPerformanceData tapi eth eth pro active dm performance data
// swagger:model tapi.eth.EthProActiveDmPerformanceData
type TapiEthEthProActiveDmPerformanceData struct {

	// This attribute contains the statistical bidirectional performnace parameters.
	ProActiveBiDirDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"pro-active-bi-dir-dm-parameters,omitempty"`

	// This attribute contains the statistical far end performnace parameters.
	ProActiveFarEndDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"pro-active-far-end-dm-parameters,omitempty"`

	// This attribute contains the statistical near end performnace parameters.
	ProActiveNearEndDmParameters *TapiEthStatisticalDmPerformanceParameters `json:"pro-active-near-end-dm-parameters,omitempty"`
}

// Validate validates this tapi eth eth pro active dm performance data
func (m *TapiEthEthProActiveDmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProActiveBiDirDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProActiveFarEndDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProActiveNearEndDmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateProActiveBiDirDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveBiDirDmParameters) { // not required
		return nil
	}

	if m.ProActiveBiDirDmParameters != nil {
		if err := m.ProActiveBiDirDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-bi-dir-dm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateProActiveFarEndDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveFarEndDmParameters) { // not required
		return nil
	}

	if m.ProActiveFarEndDmParameters != nil {
		if err := m.ProActiveFarEndDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-far-end-dm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthProActiveDmPerformanceData) validateProActiveNearEndDmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.ProActiveNearEndDmParameters) { // not required
		return nil
	}

	if m.ProActiveNearEndDmParameters != nil {
		if err := m.ProActiveNearEndDmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pro-active-near-end-dm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthProActiveDmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthProActiveDmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthProActiveDmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
