// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiEthOamPeriod tapi eth oam period
// swagger:model tapi.eth.OamPeriod
type TapiEthOamPeriod string

const (

	// TapiEthOamPeriodNr333MS captures enum value "3_33MS"
	TapiEthOamPeriodNr333MS TapiEthOamPeriod = "3_33MS"

	// TapiEthOamPeriodNr10MS captures enum value "10MS"
	TapiEthOamPeriodNr10MS TapiEthOamPeriod = "10MS"

	// TapiEthOamPeriodNr100MS captures enum value "100MS"
	TapiEthOamPeriodNr100MS TapiEthOamPeriod = "100MS"

	// TapiEthOamPeriodNr1S captures enum value "1S"
	TapiEthOamPeriodNr1S TapiEthOamPeriod = "1S"

	// TapiEthOamPeriodNr10S captures enum value "10S"
	TapiEthOamPeriodNr10S TapiEthOamPeriod = "10S"

	// TapiEthOamPeriodNr1MIN captures enum value "1MIN"
	TapiEthOamPeriodNr1MIN TapiEthOamPeriod = "1MIN"

	// TapiEthOamPeriodNr10MIN captures enum value "10MIN"
	TapiEthOamPeriodNr10MIN TapiEthOamPeriod = "10MIN"
)

// for schema
var tapiEthOamPeriodEnum []interface{}

func init() {
	var res []TapiEthOamPeriod
	if err := json.Unmarshal([]byte(`["3_33MS","10MS","100MS","1S","10S","1MIN","10MIN"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiEthOamPeriodEnum = append(tapiEthOamPeriodEnum, v)
	}
}

func (m TapiEthOamPeriod) validateTapiEthOamPeriodEnum(path, location string, value TapiEthOamPeriod) error {
	if err := validate.Enum(path, location, value, tapiEthOamPeriodEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi eth oam period
func (m TapiEthOamPeriod) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiEthOamPeriodEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
