// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiNetworkElementAttributes tapi network element attributes
// swagger:model tapi.network.element.Attributes
type TapiNetworkElementAttributes struct {

	// A label that can be used to define the role of the Network Element.
	Role string `json:"role,omitempty"`
}

// Validate validates this tapi network element attributes
func (m *TapiNetworkElementAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementAttributes) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
