// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiPhotonicMediaModulationTechnique tapi photonic media modulation technique
// swagger:model tapi.photonic.media.ModulationTechnique
type TapiPhotonicMediaModulationTechnique string

const (

	// TapiPhotonicMediaModulationTechniqueRZ captures enum value "RZ"
	TapiPhotonicMediaModulationTechniqueRZ TapiPhotonicMediaModulationTechnique = "RZ"

	// TapiPhotonicMediaModulationTechniqueNRZ captures enum value "NRZ"
	TapiPhotonicMediaModulationTechniqueNRZ TapiPhotonicMediaModulationTechnique = "NRZ"

	// TapiPhotonicMediaModulationTechniqueBPSK captures enum value "BPSK"
	TapiPhotonicMediaModulationTechniqueBPSK TapiPhotonicMediaModulationTechnique = "BPSK"

	// TapiPhotonicMediaModulationTechniqueDPSK captures enum value "DPSK"
	TapiPhotonicMediaModulationTechniqueDPSK TapiPhotonicMediaModulationTechnique = "DPSK"

	// TapiPhotonicMediaModulationTechniqueQPSK captures enum value "QPSK"
	TapiPhotonicMediaModulationTechniqueQPSK TapiPhotonicMediaModulationTechnique = "QPSK"

	// TapiPhotonicMediaModulationTechniqueNr8QAM captures enum value "8QAM"
	TapiPhotonicMediaModulationTechniqueNr8QAM TapiPhotonicMediaModulationTechnique = "8QAM"

	// TapiPhotonicMediaModulationTechniqueNr16QAM captures enum value "16QAM"
	TapiPhotonicMediaModulationTechniqueNr16QAM TapiPhotonicMediaModulationTechnique = "16QAM"

	// TapiPhotonicMediaModulationTechniquePAM4 captures enum value "PAM4"
	TapiPhotonicMediaModulationTechniquePAM4 TapiPhotonicMediaModulationTechnique = "PAM4"

	// TapiPhotonicMediaModulationTechniquePAM8 captures enum value "PAM8"
	TapiPhotonicMediaModulationTechniquePAM8 TapiPhotonicMediaModulationTechnique = "PAM8"

	// TapiPhotonicMediaModulationTechniqueUNDEFINED captures enum value "UNDEFINED"
	TapiPhotonicMediaModulationTechniqueUNDEFINED TapiPhotonicMediaModulationTechnique = "UNDEFINED"
)

// for schema
var tapiPhotonicMediaModulationTechniqueEnum []interface{}

func init() {
	var res []TapiPhotonicMediaModulationTechnique
	if err := json.Unmarshal([]byte(`["RZ","NRZ","BPSK","DPSK","QPSK","8QAM","16QAM","PAM4","PAM8","UNDEFINED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiPhotonicMediaModulationTechniqueEnum = append(tapiPhotonicMediaModulationTechniqueEnum, v)
	}
}

func (m TapiPhotonicMediaModulationTechnique) validateTapiPhotonicMediaModulationTechniqueEnum(path, location string, value TapiPhotonicMediaModulationTechnique) error {
	if err := validate.Enum(path, location, value, tapiPhotonicMediaModulationTechniqueEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi photonic media modulation technique
func (m TapiPhotonicMediaModulationTechnique) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiPhotonicMediaModulationTechniqueEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
