// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiNetworkElementSite tapi network element site
// swagger:model tapi.network.element.Site
type TapiNetworkElementSite struct {

	// none
	Latitude string `json:"latitude,omitempty"`

	// none
	Longitude string `json:"longitude,omitempty"`

	// none
	SiteName string `json:"siteName,omitempty"`
}

// Validate validates this tapi network element site
func (m *TapiNetworkElementSite) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementSite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementSite) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementSite
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
