// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOamOamServiceRef tapi oam oam service ref
// swagger:model tapi.oam.OamServiceRef
type TapiOamOamServiceRef struct {

	// none
	OamServiceUUID string `json:"oam-service-uuid,omitempty"`
}

// Validate validates this tapi oam oam service ref
func (m *TapiOamOamServiceRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamOamServiceRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamOamServiceRef) UnmarshalBinary(b []byte) error {
	var res TapiOamOamServiceRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
