// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityConnectivityServiceEndPointRef tapi connectivity connectivity service end point ref
// swagger:model tapi.connectivity.ConnectivityServiceEndPointRef
type TapiConnectivityConnectivityServiceEndPointRef struct {
	TapiConnectivityConnectivityServiceRef

	// none
	ConnectivityServiceEndPointLocalID string `json:"connectivity-service-end-point-local-id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiConnectivityConnectivityServiceEndPointRef) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiConnectivityConnectivityServiceRef
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiConnectivityConnectivityServiceRef = aO0

	// AO1
	var dataAO1 struct {
		ConnectivityServiceEndPointLocalID string `json:"connectivity-service-end-point-local-id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.ConnectivityServiceEndPointLocalID = dataAO1.ConnectivityServiceEndPointLocalID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiConnectivityConnectivityServiceEndPointRef) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiConnectivityConnectivityServiceRef)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		ConnectivityServiceEndPointLocalID string `json:"connectivity-service-end-point-local-id,omitempty"`
	}

	dataAO1.ConnectivityServiceEndPointLocalID = m.ConnectivityServiceEndPointLocalID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi connectivity connectivity service end point ref
func (m *TapiConnectivityConnectivityServiceEndPointRef) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiConnectivityConnectivityServiceRef
	if err := m.TapiConnectivityConnectivityServiceRef.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityConnectivityServiceEndPointRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityConnectivityServiceEndPointRef) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityConnectivityServiceEndPointRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
