// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityConnectivityContext tapi connectivity connectivity context
// swagger:model tapi.connectivity.ConnectivityContext
type TapiConnectivityConnectivityContext struct {

	// none
	Connection []*TapiConnectivityConnection `json:"connection"`

	// none
	ConnectivityService []*TapiConnectivityConnectivityService `json:"connectivity-service"`
}

// Validate validates this tapi connectivity connectivity context
func (m *TapiConnectivityConnectivityContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnectivityService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityConnectivityContext) validateConnection(formats strfmt.Registry) error {

	if swag.IsZero(m.Connection) { // not required
		return nil
	}

	for i := 0; i < len(m.Connection); i++ {
		if swag.IsZero(m.Connection[i]) { // not required
			continue
		}

		if m.Connection[i] != nil {
			if err := m.Connection[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connection" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiConnectivityConnectivityContext) validateConnectivityService(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectivityService) { // not required
		return nil
	}

	for i := 0; i < len(m.ConnectivityService); i++ {
		if swag.IsZero(m.ConnectivityService[i]) { // not required
			continue
		}

		if m.ConnectivityService[i] != nil {
			if err := m.ConnectivityService[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connectivity-service" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityConnectivityContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityConnectivityContext) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityConnectivityContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
