// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamGetOamServiceListOutput tapi oam get oam service list output
// swagger:model tapi.oam.GetOamServiceListOutput
type TapiOamGetOamServiceListOutput struct {

	// output
	Output *TapiOamGetOamServiceListOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi oam get oam service list output
func (m *TapiOamGetOamServiceListOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetOamServiceListOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceListOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceListOutput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceListOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiOamGetOamServiceListOutputOutput tapi oam get oam service list output output
// swagger:model TapiOamGetOamServiceListOutputOutput
type TapiOamGetOamServiceListOutputOutput struct {

	// none
	Service []*TapiOamOamService `json:"service"`
}

// Validate validates this tapi oam get oam service list output output
func (m *TapiOamGetOamServiceListOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamGetOamServiceListOutputOutput) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	for i := 0; i < len(m.Service); i++ {
		if swag.IsZero(m.Service[i]) { // not required
			continue
		}

		if m.Service[i] != nil {
			if err := m.Service[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("output" + "." + "service" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamGetOamServiceListOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamGetOamServiceListOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiOamGetOamServiceListOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
