// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOamMegRef tapi oam meg ref
// swagger:model tapi.oam.MegRef
type TapiOamMegRef struct {

	// none
	MegUUID string `json:"meg-uuid,omitempty"`
}

// Validate validates this tapi oam meg ref
func (m *TapiOamMegRef) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamMegRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamMegRef) UnmarshalBinary(b []byte) error {
	var res TapiOamMegRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
