// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNotificationGetNotificationSubscriptionServiceDetailsOutput tapi notification get notification subscription service details output
// swagger:model tapi.notification.GetNotificationSubscriptionServiceDetailsOutput
type TapiNotificationGetNotificationSubscriptionServiceDetailsOutput struct {

	// output
	Output *TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi notification get notification subscription service details output
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetNotificationSubscriptionServiceDetailsOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput tapi notification get notification subscription service details output output
// swagger:model TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput
type TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput struct {

	// none
	SubscriptionService *TapiNotificationNotificationSubscriptionService `json:"subscription-service,omitempty"`
}

// Validate validates this tapi notification get notification subscription service details output output
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput) validateSubscriptionService(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionService) { // not required
		return nil
	}

	if m.SubscriptionService != nil {
		if err := m.SubscriptionService.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output" + "." + "subscription-service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetNotificationSubscriptionServiceDetailsOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
