// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiVirtualNetworkDeleteVirtualNetworkServiceInput tapi virtual network delete virtual network service input
// swagger:model tapi.virtual.network.DeleteVirtualNetworkServiceInput
type TapiVirtualNetworkDeleteVirtualNetworkServiceInput struct {

	// input
	Input *TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput `json:"input,omitempty"`
}

// Validate validates this tapi virtual network delete virtual network service input
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkDeleteVirtualNetworkServiceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput tapi virtual network delete virtual network service input input
// swagger:model TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput
type TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput struct {

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi virtual network delete virtual network service input input
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkDeleteVirtualNetworkServiceInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
