// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNetworkElementCreatenetworkelementInputNetconfConnection tapi network element createnetworkelement input netconf connection
// swagger:model tapi.network.element.createnetworkelement.input.NetconfConnection
type TapiNetworkElementCreatenetworkelementInputNetconfConnection struct {
	TapiNetworkElementAttributes

	TapiNetworkElementConnection

	TapiNetworkElementSite
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiNetworkElementCreatenetworkelementInputNetconfConnection) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiNetworkElementAttributes
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiNetworkElementAttributes = aO0

	// AO1
	var aO1 TapiNetworkElementConnection
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.TapiNetworkElementConnection = aO1

	// AO2
	var aO2 TapiNetworkElementSite
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.TapiNetworkElementSite = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiNetworkElementCreatenetworkelementInputNetconfConnection) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.TapiNetworkElementAttributes)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.TapiNetworkElementConnection)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.TapiNetworkElementSite)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi network element createnetworkelement input netconf connection
func (m *TapiNetworkElementCreatenetworkelementInputNetconfConnection) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiNetworkElementAttributes
	if err := m.TapiNetworkElementAttributes.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiNetworkElementConnection
	if err := m.TapiNetworkElementConnection.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with TapiNetworkElementSite
	if err := m.TapiNetworkElementSite.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementCreatenetworkelementInputNetconfConnection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementCreatenetworkelementInputNetconfConnection) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementCreatenetworkelementInputNetconfConnection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
