// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamMipRef tapi oam mip ref
// swagger:model tapi.oam.MipRef
type TapiOamMipRef struct {
	TapiOamMegRef

	// none
	MipLocalID string `json:"mip-local-id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamMipRef) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiOamMegRef
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiOamMegRef = aO0

	// AO1
	var dataAO1 struct {
		MipLocalID string `json:"mip-local-id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.MipLocalID = dataAO1.MipLocalID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamMipRef) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiOamMegRef)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		MipLocalID string `json:"mip-local-id,omitempty"`
	}

	dataAO1.MipLocalID = m.MipLocalID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam mip ref
func (m *TapiOamMipRef) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiOamMegRef
	if err := m.TapiOamMegRef.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamMipRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamMipRef) UnmarshalBinary(b []byte) error {
	var res TapiOamMipRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
