// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamDeleteOamServiceInput tapi oam delete oam service input
// swagger:model tapi.oam.DeleteOamServiceInput
type TapiOamDeleteOamServiceInput struct {

	// input
	Input *TapiOamDeleteOamServiceInputInput `json:"input,omitempty"`
}

// Validate validates this tapi oam delete oam service input
func (m *TapiOamDeleteOamServiceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamDeleteOamServiceInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamDeleteOamServiceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamDeleteOamServiceInput) UnmarshalBinary(b []byte) error {
	var res TapiOamDeleteOamServiceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiOamDeleteOamServiceInputInput tapi oam delete oam service input input
// swagger:model TapiOamDeleteOamServiceInputInput
type TapiOamDeleteOamServiceInputInput struct {

	// none
	ServiceID string `json:"service-id,omitempty"`
}

// Validate validates this tapi oam delete oam service input input
func (m *TapiOamDeleteOamServiceInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamDeleteOamServiceInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamDeleteOamServiceInputInput) UnmarshalBinary(b []byte) error {
	var res TapiOamDeleteOamServiceInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
