// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthOnDemand2wayMeasurementJob tapi eth eth on demand2way measurement job
// swagger:model tapi.eth.EthOnDemand2wayMeasurementJob
type TapiEthEthOnDemand2wayMeasurementJob struct {

	// none
	OnDemandControl2waySource *TapiEthEthOnDemandMeasurementJobControlSource `json:"on-demand-control-2way-source,omitempty"`
}

// Validate validates this tapi eth eth on demand2way measurement job
func (m *TapiEthEthOnDemand2wayMeasurementJob) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOnDemandControl2waySource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthOnDemand2wayMeasurementJob) validateOnDemandControl2waySource(formats strfmt.Registry) error {

	if swag.IsZero(m.OnDemandControl2waySource) { // not required
		return nil
	}

	if m.OnDemandControl2waySource != nil {
		if err := m.OnDemandControl2waySource.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("on-demand-control-2way-source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthOnDemand2wayMeasurementJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthOnDemand2wayMeasurementJob) UnmarshalBinary(b []byte) error {
	var res TapiEthEthOnDemand2wayMeasurementJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
