// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEthOnDemandLmPerformanceData tapi eth eth on demand lm performance data
// swagger:model tapi.eth.EthOnDemandLmPerformanceData
type TapiEthEthOnDemandLmPerformanceData struct {

	// This attribute contains the results of an on-demand synthetic loss measurement job in the egress direction.
	OnDemandFarEndLmParameters *TapiEthOnDemandLmPerformanceParameters `json:"on-demand-far-end-lm-parameters,omitempty"`

	// This attribute contains the results of an on-demand synthetic loss measurement job in the ingress direction.
	OnDemandNearEndLmParameters *TapiEthOnDemandLmPerformanceParameters `json:"on-demand-near-end-lm-parameters,omitempty"`
}

// Validate validates this tapi eth eth on demand lm performance data
func (m *TapiEthEthOnDemandLmPerformanceData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOnDemandFarEndLmParameters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOnDemandNearEndLmParameters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEthOnDemandLmPerformanceData) validateOnDemandFarEndLmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.OnDemandFarEndLmParameters) { // not required
		return nil
	}

	if m.OnDemandFarEndLmParameters != nil {
		if err := m.OnDemandFarEndLmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("on-demand-far-end-lm-parameters")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEthOnDemandLmPerformanceData) validateOnDemandNearEndLmParameters(formats strfmt.Registry) error {

	if swag.IsZero(m.OnDemandNearEndLmParameters) { // not required
		return nil
	}

	if m.OnDemandNearEndLmParameters != nil {
		if err := m.OnDemandNearEndLmParameters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("on-demand-near-end-lm-parameters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEthOnDemandLmPerformanceData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEthOnDemandLmPerformanceData) UnmarshalBinary(b []byte) error {
	var res TapiEthEthOnDemandLmPerformanceData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
