// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiConnectivityCreateConnectivityServiceInput tapi connectivity create connectivity service input
// swagger:model tapi.connectivity.CreateConnectivityServiceInput
type TapiConnectivityCreateConnectivityServiceInput struct {

	// input
	Input *TapiConnectivityCreateConnectivityServiceInputInput `json:"input,omitempty"`
}

// Validate validates this tapi connectivity create connectivity service input
func (m *TapiConnectivityCreateConnectivityServiceInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityCreateConnectivityServiceInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityCreateConnectivityServiceInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityCreateConnectivityServiceInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiConnectivityCreateConnectivityServiceInputInput tapi connectivity create connectivity service input input
// swagger:model TapiConnectivityCreateConnectivityServiceInputInput
type TapiConnectivityCreateConnectivityServiceInputInput struct {

	// none
	ConnectivityConstraint *TapiConnectivityConnectivityConstraint `json:"connectivity-constraint,omitempty"`

	// none
	EndPoint []*TapiConnectivityConnectivityServiceEndPoint `json:"end-point"`

	// none
	ResilienceConstraint []*TapiConnectivityResilienceConstraint `json:"resilience-constraint"`

	// none
	RoutingConstraint *TapiPathComputationRoutingConstraint `json:"routing-constraint,omitempty"`

	// none
	State string `json:"state,omitempty"`

	// none
	TopologyConstraint *TapiPathComputationTopologyConstraint `json:"topology-constraint,omitempty"`
}

// Validate validates this tapi connectivity create connectivity service input input
func (m *TapiConnectivityCreateConnectivityServiceInputInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectivityConstraint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndPoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResilienceConstraint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoutingConstraint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopologyConstraint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInputInput) validateConnectivityConstraint(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectivityConstraint) { // not required
		return nil
	}

	if m.ConnectivityConstraint != nil {
		if err := m.ConnectivityConstraint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "connectivity-constraint")
			}
			return err
		}
	}

	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInputInput) validateEndPoint(formats strfmt.Registry) error {

	if swag.IsZero(m.EndPoint) { // not required
		return nil
	}

	for i := 0; i < len(m.EndPoint); i++ {
		if swag.IsZero(m.EndPoint[i]) { // not required
			continue
		}

		if m.EndPoint[i] != nil {
			if err := m.EndPoint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("input" + "." + "end-point" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInputInput) validateResilienceConstraint(formats strfmt.Registry) error {

	if swag.IsZero(m.ResilienceConstraint) { // not required
		return nil
	}

	for i := 0; i < len(m.ResilienceConstraint); i++ {
		if swag.IsZero(m.ResilienceConstraint[i]) { // not required
			continue
		}

		if m.ResilienceConstraint[i] != nil {
			if err := m.ResilienceConstraint[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("input" + "." + "resilience-constraint" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInputInput) validateRoutingConstraint(formats strfmt.Registry) error {

	if swag.IsZero(m.RoutingConstraint) { // not required
		return nil
	}

	if m.RoutingConstraint != nil {
		if err := m.RoutingConstraint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "routing-constraint")
			}
			return err
		}
	}

	return nil
}

func (m *TapiConnectivityCreateConnectivityServiceInputInput) validateTopologyConstraint(formats strfmt.Registry) error {

	if swag.IsZero(m.TopologyConstraint) { // not required
		return nil
	}

	if m.TopologyConstraint != nil {
		if err := m.TopologyConstraint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "topology-constraint")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiConnectivityCreateConnectivityServiceInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiConnectivityCreateConnectivityServiceInputInput) UnmarshalBinary(b []byte) error {
	var res TapiConnectivityCreateConnectivityServiceInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
