// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduOduPmPac tapi odu odu pm pac
// swagger:model tapi.odu.OduPmPac
type TapiOduOduPmPac struct {

	// Far-end Background Block Error
	FBbe int32 `json:"f-bbe,omitempty"`

	// Far-end Severely Errored Second
	FSes int32 `json:"f-ses,omitempty"`

	// Near-end Background Block Error
	NBbe int32 `json:"n-bbe,omitempty"`

	// Near-end Severely Errored Second
	NSes int32 `json:"n-ses,omitempty"`

	// UnAvailable Second
	Uas *TapiOduUasChoice `json:"uas,omitempty"`
}

// Validate validates this tapi odu odu pm pac
func (m *TapiOduOduPmPac) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUas(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduOduPmPac) validateUas(formats strfmt.Registry) error {

	if swag.IsZero(m.Uas) { // not required
		return nil
	}

	if m.Uas != nil {
		if err := m.Uas.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("uas")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduOduPmPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduOduPmPac) UnmarshalBinary(b []byte) error {
	var res TapiOduOduPmPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
