// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TapiOduOduDefectPac tapi odu odu defect pac
// swagger:model tapi.odu.OduDefectPac
type TapiOduOduDefectPac struct {

	// Backward Defect Indication
	Bdi *bool `json:"bdi,omitempty"`

	// Signal Degraded
	Deg *bool `json:"deg,omitempty"`

	// Locked
	Lck *bool `json:"lck,omitempty"`

	// Open Connection Indicator
	Oci *bool `json:"oci,omitempty"`

	// Server Signal Failure
	Ssf *bool `json:"ssf,omitempty"`

	// Trail Trace Identifier Mismatch
	Tim *bool `json:"tim,omitempty"`
}

// Validate validates this tapi odu odu defect pac
func (m *TapiOduOduDefectPac) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduOduDefectPac) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduOduDefectPac) UnmarshalBinary(b []byte) error {
	var res TapiOduOduDefectPac
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
