// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput tapi virtual network get virtual network service details input
// swagger:model tapi.virtual.network.GetVirtualNetworkServiceDetailsInput
type TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput struct {

	// input
	Input *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi virtual network get virtual network service details input
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkGetVirtualNetworkServiceDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput tapi virtual network get virtual network service details input input
// swagger:model TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput
type TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput struct {

	// none
	ServiceIDOrName string `json:"service-id-or-name,omitempty"`
}

// Validate validates this tapi virtual network get virtual network service details input input
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiVirtualNetworkGetVirtualNetworkServiceDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
