// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOduMipAugmentation1 tapi odu mip augmentation1
// swagger:model tapi.odu.MipAugmentation1
type TapiOduMipAugmentation1 struct {

	// none
	OduMipSpec *TapiOduOduMipSpec `json:"odu-mip-spec,omitempty"`
}

// Validate validates this tapi odu mip augmentation1
func (m *TapiOduMipAugmentation1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOduMipSpec(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOduMipAugmentation1) validateOduMipSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.OduMipSpec) { // not required
		return nil
	}

	if m.OduMipSpec != nil {
		if err := m.OduMipSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("odu-mip-spec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOduMipAugmentation1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOduMipAugmentation1) UnmarshalBinary(b []byte) error {
	var res TapiOduMipAugmentation1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
