// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNotificationGetNotificationSubscriptionServiceListOutput tapi notification get notification subscription service list output
// swagger:model tapi.notification.GetNotificationSubscriptionServiceListOutput
type TapiNotificationGetNotificationSubscriptionServiceListOutput struct {

	// output
	Output *TapiNotificationGetNotificationSubscriptionServiceListOutputOutput `json:"output,omitempty"`
}

// Validate validates this tapi notification get notification subscription service list output
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationGetNotificationSubscriptionServiceListOutput) validateOutput(formats strfmt.Registry) error {

	if swag.IsZero(m.Output) { // not required
		return nil
	}

	if m.Output != nil {
		if err := m.Output.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("output")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetNotificationSubscriptionServiceListOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiNotificationGetNotificationSubscriptionServiceListOutputOutput tapi notification get notification subscription service list output output
// swagger:model TapiNotificationGetNotificationSubscriptionServiceListOutputOutput
type TapiNotificationGetNotificationSubscriptionServiceListOutputOutput struct {

	// none
	SubscriptionService []*TapiNotificationNotificationSubscriptionService `json:"subscription-service"`
}

// Validate validates this tapi notification get notification subscription service list output output
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutputOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNotificationGetNotificationSubscriptionServiceListOutputOutput) validateSubscriptionService(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionService) { // not required
		return nil
	}

	for i := 0; i < len(m.SubscriptionService); i++ {
		if swag.IsZero(m.SubscriptionService[i]) { // not required
			continue
		}

		if m.SubscriptionService[i] != nil {
			if err := m.SubscriptionService[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("output" + "." + "subscription-service" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutputOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNotificationGetNotificationSubscriptionServiceListOutputOutput) UnmarshalBinary(b []byte) error {
	var res TapiNotificationGetNotificationSubscriptionServiceListOutputOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
