// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamUpdateOamJobInput tapi oam update oam job input
// swagger:model tapi.oam.UpdateOamJobInput
type TapiOamUpdateOamJobInput struct {

	// input
	Input *TapiOamUpdateOamJobInputInput `json:"input,omitempty"`
}

// Validate validates this tapi oam update oam job input
func (m *TapiOamUpdateOamJobInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamUpdateOamJobInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamUpdateOamJobInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamUpdateOamJobInput) UnmarshalBinary(b []byte) error {
	var res TapiOamUpdateOamJobInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiOamUpdateOamJobInputInput tapi oam update oam job input input
// swagger:model TapiOamUpdateOamJobInputInput
type TapiOamUpdateOamJobInputInput struct {

	// none
	JobID string `json:"job-id,omitempty"`

	// none
	OamProfile *TapiOamOamProfile `json:"oam-profile,omitempty"`

	// none
	Schedule string `json:"schedule,omitempty"`

	// none
	State string `json:"state,omitempty"`
}

// Validate validates this tapi oam update oam job input input
func (m *TapiOamUpdateOamJobInputInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOamProfile(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamUpdateOamJobInputInput) validateOamProfile(formats strfmt.Registry) error {

	if swag.IsZero(m.OamProfile) { // not required
		return nil
	}

	if m.OamProfile != nil {
		if err := m.OamProfile.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input" + "." + "oam-profile")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamUpdateOamJobInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamUpdateOamJobInputInput) UnmarshalBinary(b []byte) error {
	var res TapiOamUpdateOamJobInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
