// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiNetworkElementGetNetworkElementDetailsInput tapi network element get network element details input
// swagger:model tapi.network.element.GetNetworkElementDetailsInput
type TapiNetworkElementGetNetworkElementDetailsInput struct {

	// input
	Input *TapiNetworkElementGetNetworkElementDetailsInputInput `json:"input,omitempty"`
}

// Validate validates this tapi network element get network element details input
func (m *TapiNetworkElementGetNetworkElementDetailsInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiNetworkElementGetNetworkElementDetailsInput) validateInput(formats strfmt.Registry) error {

	if swag.IsZero(m.Input) { // not required
		return nil
	}

	if m.Input != nil {
		if err := m.Input.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("input")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementGetNetworkElementDetailsInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementGetNetworkElementDetailsInput) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementGetNetworkElementDetailsInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TapiNetworkElementGetNetworkElementDetailsInputInput tapi network element get network element details input input
// swagger:model TapiNetworkElementGetNetworkElementDetailsInputInput
type TapiNetworkElementGetNetworkElementDetailsInputInput struct {

	// none
	NetworkElementIDOrName string `json:"network-element-id-or-name,omitempty"`
}

// Validate validates this tapi network element get network element details input input
func (m *TapiNetworkElementGetNetworkElementDetailsInputInput) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TapiNetworkElementGetNetworkElementDetailsInputInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiNetworkElementGetNetworkElementDetailsInputInput) UnmarshalBinary(b []byte) error {
	var res TapiNetworkElementGetNetworkElementDetailsInputInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
