// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiOamPmThresholdData tapi oam pm threshold data
// swagger:model tapi.oam.PmThresholdData
type TapiOamPmThresholdData struct {
	TapiCommonLocalClass

	// none
	GranularityPeriod *TapiCommonTimePeriod `json:"granularity-period,omitempty"`

	// none
	IsTransient *bool `json:"is-transient,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TapiOamPmThresholdData) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 TapiCommonLocalClass
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TapiCommonLocalClass = aO0

	// AO1
	var dataAO1 struct {
		GranularityPeriod *TapiCommonTimePeriod `json:"granularity-period,omitempty"`

		IsTransient *bool `json:"is-transient,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.GranularityPeriod = dataAO1.GranularityPeriod

	m.IsTransient = dataAO1.IsTransient

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TapiOamPmThresholdData) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.TapiCommonLocalClass)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		GranularityPeriod *TapiCommonTimePeriod `json:"granularity-period,omitempty"`

		IsTransient *bool `json:"is-transient,omitempty"`
	}

	dataAO1.GranularityPeriod = m.GranularityPeriod

	dataAO1.IsTransient = m.IsTransient

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tapi oam pm threshold data
func (m *TapiOamPmThresholdData) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with TapiCommonLocalClass
	if err := m.TapiCommonLocalClass.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGranularityPeriod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiOamPmThresholdData) validateGranularityPeriod(formats strfmt.Registry) error {

	if swag.IsZero(m.GranularityPeriod) { // not required
		return nil
	}

	if m.GranularityPeriod != nil {
		if err := m.GranularityPeriod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("granularity-period")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiOamPmThresholdData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiOamPmThresholdData) UnmarshalBinary(b []byte) error {
	var res TapiOamPmThresholdData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
