// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TapiEthEth1DmThresholdData tapi eth eth1 dm threshold data
// swagger:model tapi.eth.Eth1DmThresholdData
type TapiEthEth1DmThresholdData struct {

	// This attribute contains the near end clear threshold values of the delay measurements.
	NearEnd1DmClearThreshold *TapiEthStatisticalDmPerformanceParameters `json:"near-end-1-dm-clear-threshold,omitempty"`

	// This attribute contains the near end cross threshold values of the delay measurements.
	NearEnd1DmCrossThreshold *TapiEthStatisticalDmPerformanceParameters `json:"near-end-1-dm-cross-threshold,omitempty"`
}

// Validate validates this tapi eth eth1 dm threshold data
func (m *TapiEthEth1DmThresholdData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNearEnd1DmClearThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNearEnd1DmCrossThreshold(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TapiEthEth1DmThresholdData) validateNearEnd1DmClearThreshold(formats strfmt.Registry) error {

	if swag.IsZero(m.NearEnd1DmClearThreshold) { // not required
		return nil
	}

	if m.NearEnd1DmClearThreshold != nil {
		if err := m.NearEnd1DmClearThreshold.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("near-end-1-dm-clear-threshold")
			}
			return err
		}
	}

	return nil
}

func (m *TapiEthEth1DmThresholdData) validateNearEnd1DmCrossThreshold(formats strfmt.Registry) error {

	if swag.IsZero(m.NearEnd1DmCrossThreshold) { // not required
		return nil
	}

	if m.NearEnd1DmCrossThreshold != nil {
		if err := m.NearEnd1DmCrossThreshold.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("near-end-1-dm-cross-threshold")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TapiEthEth1DmThresholdData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TapiEthEth1DmThresholdData) UnmarshalBinary(b []byte) error {
	var res TapiEthEth1DmThresholdData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
