// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// TapiOduOduSlotSize tapi odu odu slot size
// swagger:model tapi.odu.OduSlotSize
type TapiOduOduSlotSize string

const (

	// TapiOduOduSlotSizeNr1G25 captures enum value "1G25"
	TapiOduOduSlotSizeNr1G25 TapiOduOduSlotSize = "1G25"

	// TapiOduOduSlotSizeNr2G5 captures enum value "2G5"
	TapiOduOduSlotSizeNr2G5 TapiOduOduSlotSize = "2G5"
)

// for schema
var tapiOduOduSlotSizeEnum []interface{}

func init() {
	var res []TapiOduOduSlotSize
	if err := json.Unmarshal([]byte(`["1G25","2G5"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tapiOduOduSlotSizeEnum = append(tapiOduOduSlotSizeEnum, v)
	}
}

func (m TapiOduOduSlotSize) validateTapiOduOduSlotSizeEnum(path, location string, value TapiOduOduSlotSize) error {
	if err := validate.Enum(path, location, value, tapiOduOduSlotSizeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this tapi odu odu slot size
func (m TapiOduOduSlotSize) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateTapiOduOduSlotSizeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
